### ISSUE TITLE
Populate required fields

### ISSUE THREAD

**Issue by rappen** [rajyraman/Levelup-for-Dynamics-CRM#1]
Another sweet feature to this goodiebag would be a method to automatically populate required fields on a form with random data.
More than once I have cursed when having to fill in a bunch of fields, just to test creating a new record.
Having a button filling in all the empty required fields for me would save my day! And the next day probably.

**Comment by rajyraman** [comment]
You would be happy to know that it has already been done :). Ref. (https://community.dynamics.com/crm/b/magnetismsolutionscrmblog/archive/2014/12/08/microsoft-dynamics-crm-2013-populating-required-fields-with-bookmarklets)

I still have some many bookmarklets that I have not included. I will do them soon. I didn't want to overwhelm people with the initial version.
![bookmarklets](https://cloud.githubusercontent.com/assets/5035266/15500883/22bd0bc2-21ee-11e6-8353-d47788c3c6a8.png)

**Comment by rajyraman** [comment]
I have committed source with this change. If possible, can you please install the extension in Developer mode and see whether the functionality is OK? Thank you.

**Comment by rajyraman** [comment]
Fixed in v1.2
