### ISSUE TITLE
Publish to Microsoft Edge (Chromium) Store

### ISSUE THREAD

**Issue by TomMalow** [rajyraman/Levelup-for-Dynamics-CRM#100]
Microsofts new version of Edge based on Chromium have been released and it's missing this awesome extension!

Workaround: It is possible to allow extensions from other stores from the extension pane (edge://extensions/) and then find and add the extension from Chrome Web Store

**Comment by rajyraman** [comment]
I use Edge as primary and I am using the extension from Chrome store as well. I will check out what the process is, to submit the extension for approval in Edge store.

**Comment by ChrisSTIHL** [comment]
I used the option "extensions from other stores" and then installed "level up" from the chrome store. Worked perfectly and I can open the console from edge. But unfortunately the functions do not show any effect.
