### ISSUE TITLE
Missing User/role list

### ISSUE THREAD

**Issue by fpro123** [rajyraman/Levelup-for-Dynamics-CRM#101]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
    Extension Version: 3.4.6
    ----------------------------------------------------------
Hi, you previously had user/role view. This was very useful. I cannot find it in the new design?

**Comment by rajyraman** [comment]
Hi @fpro123 I moved it behind the hamburger menu.

![image](https://user-images.githubusercontent.com/5035266/73212777-0f46e300-41a3-11ea-8fd2-dfdccb2f79ec.png)
