### ISSUE TITLE
Issue with Level up

### ISSUE THREAD

**Issue by Adi-droid1** [rajyraman/Levelup-for-Dynamics-CRM#104]
Browser Version: 5.0 (Windows)
    Extension Version: 3.4.6
    ----------------------------------------------------------
    [DESCRIBE ISSUE HERE]
Record ID, Record URL and many more features of Level UP extention are not working with dynamics 365 v9 and above having unified interface.

**Comment by BetimBeja** [comment]
Hello @Adi-droid1,
can you provide more information on when the extension does not work? I have a trial environment and `Record URL` and `Record Id` work with version `3.4.6` of the extension on `Google Chrome`.

Best regards,
Betim.

**Comment by rajyraman** [comment]
Is this OnPrem or Online? It is working in Online when I checked this today.
