### ISSUE TITLE
God Mode broken on unified interface

### ISSUE THREAD

**Issue by nimro** [rajyraman/Levelup-for-Dynamics-CRM#108]
Browser Version: 5.0 (Windows)
    Extension Version: 3.4.6
    ----------------------------------------------------------

Since our Dynamics 365 instance was updated to the unified interface, God Mode appears to be broken.

Expected behaviour: God Mode selection unlocks locked fields
Actual behaviour: Fields remain locked and instead the last "tab" on the current Form is loaded

I have been able to replicate this behaviour across both Chrome and Firefox versions of the extension.

**Comment by rajyraman** [comment]
I checked this today in Online. It is working for me. Can you check in a different form and check the F12 console when you do this. Is this OnPrem?

**Comment by nimro** [comment]
I've experimented a bit and it appears to happen on any form with tabs/sections other than "General" and "Related". This is 365.

Unfortunately I can't see any related messages in the F12 console, is there a debug mode I can enable to get more telemetry out?

**Comment by MaloLocher** [comment]
I've the same issue on crm online after transition to the unified interface. you can unlock the field "product family" and edit the value. On saving the formular the standard failure that you can edit a product only in draft or new modus appears.

**Comment by BetimBeja** [comment]
The `God Mode` just unlocks the fields and does nothing more I am afraid. It doesn't bypass plugin logic or CRM logic.

**Comment by rajyraman** [comment]
@nimro - In v3.5.5 I added some code to check which tab is open and select the same tab again after unhiding all the tabs. Please check if this is still an issue.

**Comment by nimro** [comment]
@rajyraman thanks, that appears to have fixed the issue!
