### ISSUE TITLE
Levelup Stopped working with CRM 2013

### ISSUE THREAD

**Issue by zaha** [rajyraman/Levelup-for-Dynamics-CRM#112]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36
    Extension Version: 3.5.1
    ----------------------------------------------------------
When I try to use any function of Levelup I see the following error in the JS Console:

> GET http://on-premise-crm/MyOrg/api/data/v8.0/RetrieveCurrentOrganization(AccessType=@p1)?@p1=Microsoft.Dynamics.CRM.EndpointAccessType%27Default%27 404 (Not Found)
m @ levelup.extension.js:1
w.SendRequest @ levelup.extension.js:1
w.Execute @ levelup.extension.js:1
(anonymous) @ levelup.extension.js:1
n @ levelup.extension.js:1
(anonymous) @ levelup.extension.js:1
(anonymous) @ levelup.extension.js:1
(anonymous) @ levelup.extension.js:1
(anonymous) @ levelup.extension.js:1
postMessage (async)
(anonymous) @ VM234:1

This was working just fine ~2 weeks ago before my vacation. There was no change to the on-premise CRM we have in use.

**Comment by rajyraman** [comment]
This is a new functionality I added recently for getting tenantid. I haven't tested this in OnPrem at all. Is this crashing the whole extension, or do you get this error only when you choose environment details in the menu? This message won't be in crm2013.

**Comment by rajyraman** [comment]
@zaha - The call is made when the extension button is clicked. So, I have to make a change to do this only if the version is > 8.2.

**Comment by zaha** [comment]
Great, thanks. :+1:

Yeah as you said, happens only when you click any of the buttons.

**Comment by zaha** [comment]
Great, thanks. :+1:

Yeah as you said, happens only when you click any of the buttons.

**Comment by rajyraman** [comment]
@zaha - I did not update the Firefox version. So you can use it in the meantime till I push an update. https://addons.mozilla.org/en-US/firefox/addon/level-up-for-d365-power-apps/
