### ISSUE TITLE
Today CRM god mode extension bottoms have no control and does not work

### ISSUE THREAD

**Issue by shaundadman** [rajyraman/Levelup-for-Dynamics-CRM#113]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36
    Extension Version: 3.5.1
    ----------------------------------------------------------
Hi

Today Chrome CRM god mode extension bottoms have no control and does not work.

I have tried upgrading Chrome, useing different PC and the result all the same. The bottoms have no control and nothing happens upon clicking on them.

Used god mode 2 days ago and all was fine but today extension has stopped working.

Please help with this.

Thanks

Shaun

**Comment by shaundadman** [comment]
![error](https://user-images.githubusercontent.com/64238299/80170528-80bff180-862b-11ea-9898-e6b7062d4d8b.PNG)

**Comment by rajyraman** [comment]
@shaundadman - Are you on an older version of CRM as well? In that case it might be related to #112. I will fix the over the weekend. I will drop in a zip file on release so that you can sideload it while Google approves the update. It is currently taking 4 days for Google to approve due to COVID.

**Comment by shaundadman** [comment]
@rajyraman  - Thank you very much for your prompt response.

Yes, we are on CRM 2015.

I will wait for the release then..

Thanks again

**Comment by rajyraman** [comment]
@shaundadman - The Firefox version has not been updated yet. So, you can use it in the meantime. https://addons.mozilla.org/en-US/firefox/addon/level-up-for-d365-power-apps/

**Comment by shaundadman** [comment]
@rajyraman - Thanks very much for this.. Have a great weekend!

**Comment by rajyraman** [comment]
@shaundadman - Kicked off the publish. You can side-load the extension from Releases in the mean time and let me know whether the issue is fixed.

**Comment by shaundadman** [comment]
@rajyraman - Sorry, I am new here and don't know how to download the release.. 

Downloaded a wrong one and Chrome complained about java manifest.

Can you please advise?

Thanks

**Comment by rajyraman** [comment]
Download the zip file from releases area and unzip the file to a folder. Then follow these steps https://www.cnet.com/how-to/how-to-install-chrome-extensions-manually/

**Comment by shaundadman** [comment]
@rajyraman - Thank you very much.. I managed to load the new extension to Chrome and confirm that ver. 3.5.2 works perfectly fine with CRM 2015 without any problems.

Have a nice weekend
