### ISSUE TITLE
Command Debugger in View Tab

### ISSUE THREAD

**Issue by LinnZawWin** [rajyraman/Levelup-for-Dynamics-CRM#115]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 Edg/81.0.416.72
    Extension Version: 3.5.2
    ----------------------------------------------------------
Currently, the "Command Debugger" command in the Forms tab shows the following error (which is acceptable since all commands under the Forms tab are performed in the context of a form)
"This command can only be performed in the context of a form"

But another "Command Debugger" command is required in the View tab to debug the command bar buttons in the home page.

**Comment by rajyraman** [comment]
@LinnZawWin - Moving this to left nav. Also adding a blur for view.
![image](https://user-images.githubusercontent.com/5035266/81646463-9bd59280-946e-11ea-9a5c-d982ed2938fa.png)
