### ISSUE TITLE
GodMode Invoice entity

### ISSUE THREAD

**Issue by rvroemen** [rajyraman/Levelup-for-Dynamics-CRM#116]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
    Extension Version: 3.5.2
    ----------------------------------------------------------
I tried to use GodMode on the Invoice entity (URL with forceUCI = 1). The default tab is Summary, however, when selecting GodMode, tab Details is opened. When turning back to the Summary tab, the GodMode is inactive again...

**Comment by rajyraman** [comment]
@rvroemen - In v3.5.5 I added some code to check which tab is open and select the same tab again after unhiding all the tabs. Please check if this is still an issue.
