### ISSUE TITLE
God Mode Locked 

### ISSUE THREAD

**Issue by scottglisson** [rajyraman/Levelup-for-Dynamics-CRM#120]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
    Extension Version: 3.5.2
    ----------------------------------------------------------
    When I go to this extension there is a gold lock icon next to the God Mode function and it's not allowing me to use it.  Is this not available anymore?  Thanks.

**Comment by rajyraman** [comment]
@scottglisson - That is just an emoji that I put on the tooltip.
