### ISSUE TITLE
Level Up extension not working on Dynamcis 365 v9 unified interface

### ISSUE THREAD

**Issue by SallyVG** [rajyraman/Levelup-for-Dynamics-CRM#121]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
    Extension Version: 3.5.2
    ----------------------------------------------------------
Reinstalled Level up and when clicking on various options e.g. logical names inside of Dynamics 365 UI, nothing happens.  Has anyone else experienced this issue

**Comment by rajyraman** [comment]
@SallyVG - I am unable to reproduce this. Did you refresh the page after installing?
