### ISSUE TITLE
God Mode Locked

### ISSUE THREAD

**Issue by scottglisson** [rajyraman/Levelup-for-Dynamics-CRM#122]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
    Extension Version: 3.5.2
    ----------------------------------------------------------
God Mode now has a lock icon next to it and I can't use it.  Is this something fairly new?  How do I unlock it?

![2020-07-14_9-01-57](https://user-images.githubusercontent.com/44215725/87435087-e24f8680-c5b0-11ea-8b25-8899f1ae9ad3.png)

**Comment by rajyraman** [comment]
@scottglisson - That is just an emoji. I am able to use it on Unified Interface. There might be some issues with legacy forms that have a ribbon. Is it not working for you? What Dynamics version are you on?

**Comment by scottglisson** [comment]
Thank you for the response.  It seems to be working now.  There was a day or two that it wasn’t and I assumed it was because of that “lock”, but I’ve used it since and it’s been fine.  Thank you for reaching out!

Scott Glisson
Director, Enterprise Applications
205-248-1568 (D)
Randall-Reilly | 3200 Rice Mine Road NE, Tuscaloosa, AL 35406
randallreilly.com | facebook.com/randallreilly | twitter.com/randallreilly
