### ISSUE TITLE
Show Optionset Values Not Working on Tabs in v9 UCI

### ISSUE THREAD

**Issue by mhammons** [rajyraman/Levelup-for-Dynamics-CRM#125]
Hi, when trying to use SHOW OPTIONSET VALUES in new v9 UCI when on a tab, it is not showing the all of the optionsets from that tab. A few are displayed but many are missing.

Steps to duplicate:
1. Open a contact record.
2. Go to Details tab
3. Click Level Up
4. It's missing many optionsets
5. The missing ones are under the Contact Preferences Section 

![missingoptionsetslevelup](https://user-images.githubusercontent.com/36681041/89453867-da0ce600-d72d-11ea-9b1a-0adb3ecbe5fc.png)

**Comment by rajyraman** [comment]
getAttributeType() for two options seems to be boolean, rather than optionset. So I need to change this to use getControlType().

![image](https://user-images.githubusercontent.com/5035266/89858538-4aaa7b80-dbe2-11ea-8228-29696cbc22e8.png)
