### ISSUE TITLE
Can't access the workflows and actions through Navigation - Processes

### ISSUE THREAD

**Issue by ccsshing** [rajyraman/Levelup-for-Dynamics-CRM#128]
Hi, 
If you use "Navigation - Processes", and open records with Category = "Workflow" or "Action", the page will re-direct to an error page as shown below. But if you use default solution - processes to view the same process, it would be fine.
![image](https://user-images.githubusercontent.com/10535072/89857685-4e80d280-dbcf-11ea-8f23-9a1f3e4ffece.png)

Note that Business Process Flow are able to view in both default solution and "Navigation - Processes".

**Comment by rajyraman** [comment]
@ccsshing - This button just opens https://[ORGURL]/main.aspx?appid=[APPID]&etn=workflow&pagetype=entitylist on a model driven app. Does navigation to this URL give you the same error?

**Comment by ccsshing** [comment]
> @ccsshing - This button just opens https://[ORGURL]/main.aspx?appid=[APPID]&etn=workflow&pagetype=entitylist on a model driven app. Does navigation to this URL give you the same error?

The process page can be loaded successfully. 
![image](https://user-images.githubusercontent.com/10535072/89869410-e8a04500-dbe6-11ea-91b8-34cae3df2017.png)

But when I clicked the records (or processes) of Category = workflow / action, for example the "Sales Insights delete flow" in the above picture, there is a new window pop-up, and is re-directed to the error page soon. 

The record URL before re-direction: 
https://[ORGURL]/Tools/ProcessControl/UnifiedProcessDesigner.aspx?id=[ID]&appid=[APPID]&parkingsolutionId=[SolutionID]

will be re-directed to
https://[ORGURL]/_common/error/errorhandler.aspx?BackUri=[ORGURL]%2fuclient%2fblank.htm%3fv%3d1.4.1144-2007.3&ErrorCode=&Parm0=%0d%0a%0d%0aError%20Details%3a%20An%20unhandled%20exception%20occurred%20during%20the%20execution%20of%20the%20current%20web%20request.%20Please%20review%20the%20stack%20trace%20for%20more%20information%20about%20the%20error%20and%20where%20it%20originated%20in%20the%20code.&RequestUri=https://[ORGURL]/Tools/ProcessControl/UnifiedProcessDesigner.aspx?id=[ID]&appid=[APPID]&parkingsolutionId=[ParkingSolutionID]]&user_lcid=1033

The record URL which can successfully open the record (in default solution - process):
https://[ORGURL]/sfa/workflow/edit.aspx?appSolutionId=%7b[SameAsParkingSolutionID]%7d&id=%7b[ID]%7d
