### ISSUE TITLE
God Mode is not working Level up for Dynamics 365/Power Apps v3.5.3

### ISSUE THREAD

**Issue by gpmoffatt** [rajyraman/Levelup-for-Dynamics-CRM#130]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.42 Safari/537.36 Edg/86.0.622.19
    Extension Version: 3.5.3
    ----------------------------------------------------------
When Using God Mode - nothing Happens

**Comment by anuprakash** [comment]
I am facing the same issue. I have attached the Browser console output for reference
![D365_Godmode_Console_Error](https://user-images.githubusercontent.com/14291560/93785798-1a77e300-fc4c-11ea-912f-353c3e7290f3.png)

**Comment by rajyraman** [comment]
I am still not able to repro this on a custom form. Are you using a specific form or specific app? Can you please post a small video or what you are trying to do? Other option is to do a screenshare session. @gpmoffatt @anuprakash

**Comment by mwe22114** [comment]
I am finding that God mode is no longer unlocking locked fields

**Comment by rajyraman** [comment]
Can please share the region and version number of your environment?

**Comment by mwe22114** [comment]
Hi
Database version
9.1.0000.22845

Region
Australia

Regards

Mark

**Comment by mwe22114** [comment]
My previous message was for Production.
Also we have enabled the pre-release version in our sandbox with Database version
9.1.0000.22845 and it isn't working there either.

Regards

Mark

**Comment by rajyraman** [comment]
I tried this today and it works. I am on Server version: 9.1.0000.22845, and Client version: 1.4.1440-2008.5. I tried this in both Chrome and Edge.
![2020-09-27_5-33-13](https://user-images.githubusercontent.com/5035266/94348929-937b9e00-0083-11eb-8bdf-c255cee8a3b1.gif)

**Comment by rajyraman** [comment]
@mwe22114 - Can you please sideload the extension from latest release (https://github.com/rajyraman/Levelup-for-Dynamics-CRM/releases/latest) and see whether it fixes the issue?

**Comment by mwe22114** [comment]
Thanks for the update but I don’t know how to install the extension in this manner. From what I could find online it possibly involved editing the registry of my machine. My laptop is a company laptop and I do not have permission to edit the registry manually.

I notice this is point release higher than the one available in the Chrome store. Are you able to make this available so I can update from there?

Regards

Mark

**Comment by rajyraman** [comment]
@mwe22114 - It is not difficult. On the extension tab you can sideload the extension by pointing it to the unzipped folder location (after downloading the zip from release). I have kicked off the publish as well, but due to the turn around time for approval, it would take couple of weeks for another approval if the fix does not work.

![image](https://user-images.githubusercontent.com/5035266/94378137-4aeae000-016a-11eb-881a-340f23bd64f8.png)

**Comment by rajyraman** [comment]
@mwe22114 - The new version is already up on Firefox. https://addons.mozilla.org/en-US/firefox/addon/level-up-for-d365-power-apps/. You can test in this if you have Firefox.

**Comment by mwe22114** [comment]
Thanks, I have updated and God mode is working again

**Comment by anggazan** [comment]
> @mwe22114 - Can you please sideload the extension from latest release (https://github.com/rajyraman/Levelup-for-Dynamics-CRM/releases/latest) and see whether it fixes the issue?

Hi, i updated chrome extension to recent version but God Mode still not work in crm5.dynamics.com server

**Comment by mwe22114** [comment]
I can confirm that it is now working for me in Chrome. I did need to shut the browser down first but other than that ii is working fine for me now.

**Comment by anggazan** [comment]
> I can confirm that it is now working for me in Chrome. I did need to shut the browser down first but other than that ii is working fine for me now.

yes..i can confirm too with this way...close and reopen browser

**Comment by gpmoffatt** [comment]
Hi team.  Legends  everything is working again




Cheers 


Moff




Get Outlook for Android







On Tue, Sep 29, 2020 at 7:06 AM +1000, "Natraj Yegnaraman" <notifications@github.com> wrote:















Closed #130.
