### ISSUE TITLE
Level up on CRM 2015 stopped working

### ISSUE THREAD

**Issue by shaundadman** [rajyraman/Levelup-for-Dynamics-CRM#132]
Hi

Since this morning God mode on Level up for Dynamics has stopped working (could be the result of changes over the weekend).
Back in April this happened again and @rajyraman fixed it

@rajyraman can you please assist with this like you did last time.
Also this time this extension still works on Firefox as you advised last time which I am using for now.

Thank you again

Shaun

**Comment by rajyraman** [comment]
@shaundadman - Firefox and Edge are already on 3.5.4. Google has still not approved the update yet. So, if you are still on 3.5.3 you will see this issue until the update is approved.

**Comment by shaundadman** [comment]
@rajyraman - Thank you for this update.
I will be using Firefox then until Google approves this.

Thank you again for your help with this.

Cheers

**Comment by Yuwenhao** [comment]
In Chrome I got this err:
chrome-extension://bjnkkhimoaclnddigpphpgkfgeggokam/scripts/levelup.extension.js:1317 TypeError: Cannot read property 'tabs' of null
    at Forms../app/scripts/inject/levelup.forms.ts.Forms.godMode (chrome-extension://bjnkkhimoaclnddigpphpgkfgeggokam/scripts/levelup.extension.js:418)
    at chrome-extension://bjnkkhimoaclnddigpphpgkfgeggokam/scripts/levelup.extension.js:1303
    at step (chrome-extension://bjnkkhimoaclnddigpphpgkfgeggokam/scripts/levelup.extension.js:1237)
    at Object.next (chrome-extension://bjnkkhimoaclnddigpphpgkfgeggokam/scripts/levelup.extension.js:1218)
    at fulfilled (chrome-extension://bjnkkhimoaclnddigpphpgkfgeggokam/scripts/levelup.extension.js:1209)

In Firefox:
TypeError: Xrm.Page.ui is null
    godMode levelup.forms.ts:70
    ts levelup.extension.ts:99
    step levelup.extension.ts:33
    verb levelup.extension.ts:14
    fulfilled levelup.extension.ts:5
    promise callback*step levelup.extension.ts:7
    __awaiter levelup.extension.ts:8
    __awaiter levelup.extension.ts:4
    ts levelup.extension.ts:44

**Comment by shaundadman** [comment]
@rajyraman Sorry, just noticed that Chrome is also on  3.5.4 and the issue persist.

Thanks

**Comment by rajyraman** [comment]
@shaundadman - I am not getting any error in Online. Are you getting the same error as @Yuwenhao? I don't have any CRM2015 instance where I can test this.

**Comment by rajyraman** [comment]
@shaundadman, @Yuwenhao  - I think I made a stupid mistake. Can you sideload the extension and test it in another 15 mins?

**Comment by Yuwenhao** [comment]
@rajyraman OK, what do Ineed to do

**Comment by Yuwenhao** [comment]
@rajyraman  I am in CRM2016 v8.2  on-premises

**Comment by rajyraman** [comment]
@Yuwenhao @shaundadman - Please sideload https://github.com/rajyraman/Levelup-for-Dynamics-CRM/releases/tag/refs%2Fheads%2Fmaster and check

**Comment by shaundadman** [comment]
@rajyraman - Just loaded it and it seems like we are back in business.

It behaves differently though, It hides behind Extensions icon. Once clicked, the menu appears and works perfectly fine.

Thank you

**Comment by rajyraman** [comment]
I will push this version to all the three stores now.

**Comment by shaundadman** [comment]
@rajyraman - Great, thank you.
Also I just needed to pin it so it appears on the bar.

**Comment by Yuwenhao** [comment]
@rajyraman  I have updated to v3.5.5 and God mode is working again.
Thank you
