### ISSUE TITLE
Impersonation does not work if user is not added to root business unit

### ISSUE THREAD

**Issue by handnavi** [rajyraman/Levelup-for-Dynamics-CRM#143]
Hi,

the fetchXML used in code to check for canImpersonate does only work if the user is added to the root business unit of the system.

The query wont return any result if this is not the case.

**Comment by rajyraman** [comment]
@handnavi - Removed the privilege check. Please check again on Chrome.

**Comment by handnavi** [comment]
@rajyraman: Thank you. It is working now on Chrome! :-)
