### ISSUE TITLE
Unable to turn-off Impersonation

### ISSUE THREAD

**Issue by Power-Maverick** [rajyraman/Levelup-for-Dynamics-CRM#144]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36
    Extension Version: 3.5.6
    ----------------------------------------------------------
Impersonation worked great. (Thanks @DynamicsNinja)
But once enabled I an unable to turn it off. Is there a trick to it?

**Comment by jacobbates** [comment]
Seeing something similar to @Power-Maverick. Maybe related to the canImpersonate fetchxml returning false once Dynamics sets the session user as the impersonated user? Going to the 'My Roles' page when impersonating shows a fetch is returning the impersonated user's roles. The issue hasn't occurred for me yet if impersonating a user who also has the privileges to impersonate (so canImpersonate fetch would still be true)

Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36 Edg/88.0.705.56
    Extension Version: 3.5.6

**Comment by DynamicsNinja** [comment]
I managed to lose impersonation tab once in Chrome today, but still can't reproduce this issue. Is that your case too? Opening another tab with different instance will clear the extension cache so it could be a temporary fix for now.

**Comment by Power-Maverick** [comment]
Tried to close the browser and also clear the cache but unable to lose impersonation.

**Comment by rajyraman** [comment]
@Power-Maverick @jacobbates @jacobbates  - Published a new version v3.5.7 which rolls back the privilege check. I have submitted this in both Chrome and Edge today. Let see whether they approve it quickly. It should fix #143 as well. If the user does not have the priv to impersonal they cannot access the app any way. All they see is a big error. So, I don't think we protect the user from doing this.

**Comment by Power-Maverick** [comment]
Thanks for the quick fix. Much appreciated.

**Comment by rajyraman** [comment]
New version is out on Chrome. Edge is still under review

**Comment by Power-Maverick** [comment]
New changes works perfectly. Liked the nice indicator with initials.
