### ISSUE TITLE
Issue turning off impersonation

### ISSUE THREAD

**Issue by martinmcmahon** [rajyraman/Levelup-for-Dynamics-CRM#145]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36
    Extension Version: 3.5.7
    ----------------------------------------------------------
    I tried the new impersonate feature (love it!) but when finished I turned impersonate off. It was only the next day I noticed i was still impersonating. I needed to turn back on and impersonate myself to get back to normal.

**Comment by rajyraman** [comment]
This is a bug. It is related to #144. Please update to the latest version on Chrome and it should be OK. The Edge version that fixes this issue has not be approved yet.

**Comment by martinmcmahon** [comment]
Yes, working now. I must have tried before the update. It appears that yesterday 'User to Impersonate' had disappeared when i turned off impersonation, now it is being retained. If I turn off when there is a value it gets me back to me. This will be extremely useful. Huge thanks to all involved.
