### ISSUE TITLE
Impersonate bug

### ISSUE THREAD

**Issue by sjoerdpoppelaars** [rajyraman/Levelup-for-Dynamics-CRM#146]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36
    Extension Version: 3.5.7
    ----------------------------------------------------------
    New impersonate feature is not accessible for me, not pulling in the users, would be a very helpful feature though! love the developments!

**Comment by DynamicsNinja** [comment]
I heard about this issue from another user too, but we didn't found the resolution. Can you provide us a bit more info about the issue. Do you experience it on all instances or only one? Online or on-prem? Which user do you use, admin or a regular user with all permissions needed?

Since it's not a common issue we would really want to get as much info as possible about the issue.

**Comment by rajyraman** [comment]
@sjoerdpoppelaars - Please add some screenshots.

**Comment by sjoerdpoppelaars** [comment]
Hi there,

First of all let me say, great chrome extension! Very useful, and the new
impersonate feature would be very helpful in testing : )

So I tried this as an admin user myself with full rights, on a Dynamics 365
online production environment:
[image: image.png]
The feature is available, but no users are pulled in, so I'm not able to
select any users. I tried the same on a sandbox instance from our tenant,
but got the same result.

Kind regards,

Sjoerd Poppelaars (NL)

Op wo 10 feb. 2021 om 12:57 schreef Natraj Yegnaraman <
notifications@github.com>:

**Comment by Suxsem** [comment]
Same issue for me. Can I help you somehow?

**Comment by DynamicsNinja** [comment]
Did you get any errors in the developer console?

**Comment by Suxsem** [comment]
@DynamicsNinja no I can't see any error in console.
Anyway, I suspect that the issue only occurs when Dynamics is opened in "incognito mode" (of course you have to enable levelup to execute in incognito mode from the extension options).
I see that in normal sessions a systemusers query is executed when the "impersonate" tab is first open. In incognito no such request is made.

**Comment by DynamicsNinja** [comment]
@Suxsem thanks for the incognito info, that's definitely the case here. I managed to reproduce the issue in incognito mode.

**Comment by Suxsem** [comment]
@DynamicsNinja great I'm glad it helped!
Thank you for your effort, I think impersonation is one of the most requested features from all Dynamics developers. It already helped us tracking down an infamous bug from one of your client.
I already tried to make something similar some years ago without success, I'm very glad you did!

**Comment by Suxsem** [comment]
hello @rajyraman @DynamicsNinja,
do you have any update on this issue? Thank you guys!

**Comment by xrmthomas** [comment]
This issue started showing up for me today. It happens in both incognito as regular mode. The impersonation option is available, but as @sjoerdpoppelaars stated no users are being pulled in: 
![image](https://user-images.githubusercontent.com/43544903/111976772-4a704800-8b02-11eb-8465-912f63cb11c7.png)

**Comment by MatthewTheRaven** [comment]
I have the same issue, but for me it's intermittent. I've had it work and not work in the same browser on the same site, without a clear distinction on why it works or not. When it does not work, it looks the same as the screenshot posted by xrmthomas above. I'm curious if it could be related to the number of users if it's loading the full list every time. I have 2000+ users in my instance.

**Comment by sjoerdpoppelaars** [comment]
For me it is working since a couple weeks, we have about 500 users FYI!

Op do 8 apr. 2021 15:53 schreef Matthew Noel ***@***.***>:

**Comment by AngelRodriguez8008** [comment]
scripts/options.js:186 (anonymous function)
Error handling response: TypeError: Cannot read properties of undefined (reading 'text')
``` chrome.storage.local.set((_a = {},
                _a[_interfaces_types__WEBPACK_IMPORTED_MODULE_0__["LocalStorage"].isImpersonating] = checkboxElement.checked,
                _a[_interfaces_types__WEBPACK_IMPORTED_MODULE_0__["LocalStorage"].userName] = selectedUser.options[selectedUser.selectedIndex].text,    <--- hier
                _a));```

**Comment by rvk-David** [comment]
Hi
I"ve been handed this, and we are having the same problem, actually nothing works in the ext.
Our consultant has no problem but anyone who logs directly into 365 it does not work.
Any one find the answer?

Thanks
David

**Comment by MatthewTheRaven** [comment]
After more testing, this is happening on our end because we have more than 5000 users in some environments and the query that gets the names fails because of the 5000 item limit in fetchxml and it’s seems to not handling paging correctly.

**Comment by mrunalinivvn** [comment]
I am unable to impersonate the user. I see that there is some change in the way page looks now. I need to enter the mail id to impersonate. Even if I enter the email id, and toggle the button Impersonate, it shows as impersonating but nothing happens.
Please help..!
<img width="391" alt="image" src="https://user-images.githubusercontent.com/35772472/225261489-e251514f-ba88-4503-b6ac-42a4e96941a5.png">

**Comment by rvk-David** [comment]
I am so sorry, I haven’t had a chance to update this.
I will look at this today.

Sorry
David
