### ISSUE TITLE
Impersonate Stuck

### ISSUE THREAD

**Issue by markpws** [rajyraman/Levelup-for-Dynamics-CRM#149]
Browser Version: 5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36
    Extension Version: 3.5.7
    ----------------------------------------------------------
    I impersonated a user, then turned off impersonation, but now Level Up does not think I am impersonating anybody but I am stuck as the user i originally impersonated:
<img width="936" alt="Screen Shot 2021-03-09 at 9 46 37 AM" src="https://user-images.githubusercontent.com/35499321/110488764-ca3af300-80bc-11eb-933d-22b6cf2024b2.png">

**Comment by markpws** [comment]
I was at least able to get back to being logged in as myself by choosing to impersonate myself (Mark Phillips):
<img width="935" alt="Screen Shot 2021-03-09 at 9 54 59 AM" src="https://user-images.githubusercontent.com/35499321/110490249-1d617580-80be-11eb-87d3-c3eafcf5c9ac.png">

**Comment by DynamicsNinja** [comment]
Quick fix to this issue it to turn on impersonate followed by turn off afterwards and you will be back to normal again.
