### ISSUE TITLE
The user list is not populating in the impersonate feature.

### ISSUE THREAD

**Issue by borovez** [rajyraman/Levelup-for-Dynamics-CRM#156]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4471.0 Safari/537.36 Edg/91.0.864.1
    Extension Version: 3.5.7
    ----------------------------------------------------------
The user list is not populating in the impersonate feature.

**Comment by anasufovic** [comment]
Same issue, we have a larger org and the list doesn't display all users. A user search feature would help to avoid having to query the entire list ahead of time.
