### ISSUE TITLE
Impersonation user list does not appear 

### ISSUE THREAD

**Issue by jruana** [rajyraman/Levelup-for-Dynamics-CRM#169]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
    Extension Version: 3.5.7
    ----------------------------------------------------------
When Clicking on the Impersonate button, appears a green line and there is no way to select the user to impersonate

![image](https://user-images.githubusercontent.com/38654093/124757381-ccf40a80-df2d-11eb-85fa-b689669f897f.png)

**Comment by dornell2020** [comment]
same problem here
