### ISSUE TITLE
Impersonation not working on D365 On-Prem 8.2

### ISSUE THREAD

**Issue by prasath2k4** [rajyraman/Levelup-for-Dynamics-CRM#170]
**Describe the bug**
Impersonation not working on D365 On-Prem 8.2. Below is what appears in browser console. 

![image](https://user-images.githubusercontent.com/7643239/125816572-38f8ced8-0b5a-49f0-8976-2da79bc6a04c.png)

**Desktop (please complete the following information):**
 - Browser - Edge
 - Dynamics 365/Power Apps Version - D365 On-Prem 8.2
 - Admin/Non-admin - Both
 - Online/On-Premise - On-Premise
 - Unified Inferface/Classic Interface - Classic
 - Model Driven App/Classic App - Model Driven
 - Entity name, if it is an out-of-the-box entity - its a custom entity

**To Reproduce**
When you are the CRM page, click on Level Up extention and turn on the Impersonating. 

**Expected behavior**
User list must be shown

**Screenshots**

![image](https://user-images.githubusercontent.com/7643239/125817037-5143b86d-683c-4c93-98cd-6737c8ee408d.png)

**Comment by rajyraman** [comment]
@prasath2k4 - People have reported the same issue. But, I can't repro it on my environment. Can you DM me on Twitter (rajyraman) and we can set some time up to see what is happening via Teams?

**Comment by BetimBeja** [comment]
The problem is in this line:
https://github.com/rajyraman/Levelup-for-Dynamics-CRM/blob/f684c12cf35a465494192dccfe30a761316bb690/app/scripts/inject/levelup.servicecalls.ts#L140


as per Typescript documentation:
![image](https://user-images.githubusercontent.com/11160171/127968021-562d0fa3-53e0-4f35-845d-91f0539d1e7b.png)

it should be:
```typescript
  this.utility.Xrm?.Utility?.getGlobalContext?.().getUserId() ?? this.utility.Xrm.Page.context.getUserId();
```
