### ISSUE TITLE
Impersonate not showing team members after one use

### ISSUE THREAD

**Issue by clwmarshall** [rajyraman/Levelup-for-Dynamics-CRM#172]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36
    Extension Version: 3.5.7
    ----------------------------------------------------------
Unable to use Impersonate feature after using one use. Have cleared cookies, tried incognito, but still not working.

**Comment by ajtgh** [comment]
I'm seeing the same or a very similar issue. The user I originally chose to impersonate disappears from the list after I enable/disable impersonation. Only way I could get around it is to create a new Chrome profile. Not ideal of course, especially as LevelUp has to be installed in the new profile each time.

**Comment by dornell2020** [comment]
same problem here
