### ISSUE TITLE
Impersonate Issue with available users

### ISSUE THREAD

**Issue by glissa3000** [rajyraman/Levelup-for-Dynamics-CRM#175]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
    Extension Version: 3.5.7
    ----------------------------------------------------------
No users available in the dropdown

**Comment by dornell2020** [comment]
same problem here

**Comment by rajyraman** [comment]
@glissa3000 - Please refer https://twitter.com/DynamicsNinja/status/1426091615144271876?s=20 and see if that works

![image](https://user-images.githubusercontent.com/5035266/131657863-6bfbaaa9-b39b-401a-9ff3-fc1d22da790c.png)
