### ISSUE TITLE
can't see any user to impersonate 

### ISSUE THREAD

**Issue by dornell2020** [rajyraman/Levelup-for-Dynamics-CRM#176]
Browser Version: 5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
    Extension Version: 3.5.7
    ----------------------------------------------------------
I can't see a user list to select in order to impersonate. Any ideas?

**Comment by BetimBeja** [comment]
Duplicate of #169 

Also more details like: 
- OnPremise/OnLine 
- is your current user an admin?

would be helpful

**Comment by rajyraman** [comment]
@dornell2020 - Please refer https://twitter.com/DynamicsNinja/status/1426091615144271876?s=20 and see if that works

![image](https://user-images.githubusercontent.com/5035266/131657863-6bfbaaa9-b39b-401a-9ff3-fc1d22da790c.png)
