### ISSUE TITLE
Impersonate appears to have stopped working

### ISSUE THREAD

**Issue by ogradyliam5** [rajyraman/Levelup-for-Dynamics-CRM#177]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36 Edg/94.0.992.31
    Extension Version: 3.5.7
    ----------------------------------------------------------
Hi team, I think the Impersonate feature has stopped working the last few days. I have tried removing the extension and adding again. Is there anything else I can try?

Thanks,
Liam

![image](https://user-images.githubusercontent.com/28402336/135232478-4cd1fce9-af47-4126-94b8-b50663cb44aa.png)

**Comment by AngelR0909** [comment]
Hi, same thing here.
Very annoying 😢
