### ISSUE TITLE
Impersonate another user

### ISSUE THREAD

**Issue by kcscholars** [rajyraman/Levelup-for-Dynamics-CRM#183]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36
    Extension Version: 3.5.8
    ----------------------------------------------------------
I was able to successfully impersonate another user, but now I'm not able to turn it off. I've shut down and reopened the browser, logged out and then back in to D365 and it still has me impersonating the user. I tried to "impersonate back" to my user but now there are no users displaying to select from. Any idea on how I can get it to switch back to my user instance?

**Comment by BetimBeja** [comment]
Hello @kcscholars,
![image](https://user-images.githubusercontent.com/11160171/140296094-17da7f3b-f520-4841-a36d-a113426fdfe9.png)
You should be able to turn off impersonation by switching the impersonating to off
![image](https://user-images.githubusercontent.com/11160171/140296340-1c51437d-1bbc-4e11-9b95-8b50e177f3fb.png)
If you cannot do this maybe we need more details on how to replicate the problem.

**Comment by kcscholars** [comment]
Yeah, well that was the first step I tried. The problem is that it doesn’t populate the users so that I can select myself. Here’s what I see when I try:
***@***.***

-Michael

**Comment by kcscholars** [comment]
Hello,

I’m still stuck in the user I impersonated. I need help to revert it back please.

-Michael

**Comment by BetimBeja** [comment]
Try Disabling the extension, and enabling it again:
![image](https://user-images.githubusercontent.com/11160171/141235062-b33b2567-71c5-49ef-99a1-391a58547f3b.png)
It should reset anything related to the tool. If it doesn't work then your problem might be related to something else, not related to impersonation using Level up for Dynamics

**Comment by kcscholars** [comment]
Uninstalling and reinstalling the extension worked.
