### ISSUE TITLE
When I impersonate, I cannot switch it off completely and I get stuck in the user I was before.

### ISSUE THREAD

**Issue by AlessandroMarc** [rajyraman/Levelup-for-Dynamics-CRM#189]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
    Extension Version: 3.5.8
    ----------------------------------------------------------
    [DESCRIBE ISSUE HERE]

**Comment by DynamicsNinja** [comment]
Try to select any user from the dropdown, turn impersonation on, and shortly back to off again. You should be back to the original user now.

If you can't select the user (list is empty), unfortunately, it's a weird bug, you need to kill all your Chrome/Edge processes and open it again to make the extension reinitialize to the original state.

**Comment by AlessandroMarc** [comment]
Thank you!

Alessandro Marchesin
