### ISSUE TITLE
Dirty Fields doesn't find the fields

### ISSUE THREAD

**Issue by rappen** [rajyraman/Levelup-for-Dynamics-CRM#2]
Trying the Dirty Fields method.
In my case two attributes are found to be dirty, but they are not highlighted, instead an alert informs that those two attributes will not be saved.
I guess this line fails: https://github.com/rajyraman/Levelup-for-Dynamics-CRM/blob/master/crmmethods.js#L153

**Comment by rajyraman** [comment]
It is a known issue. get_chromeElement is undocumented and works only in CRM2015. I will figure out a way to grab the outer dom of the attribute and highlight it.

**Comment by rajyraman** [comment]
Fixed in v1.2
