### ISSUE TITLE
Impersonate doesn't work

### ISSUE THREAD

**Issue by paulhuynh** [rajyraman/Levelup-for-Dynamics-CRM#209]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
    Extension Version: 3.5.8
    ----------------------------------------------------------
   Impersonate is no longer working. Either MS Edge or Chrome.
   The screen doesn't refresh after selecting a user and toggled the Impersonate button.

Thanks

**Comment by Ian-O** [comment]
I am having what appears to be the same issue.
After selecting a User the screen doesn't refresh.
The uses initials are displayed over the Level Up icon, my initals are displayed within CE.
![image](https://user-images.githubusercontent.com/21371134/183896405-ac0fe2fd-370a-488d-ae81-2ba17f2bfe09.png)



tested in Google Chrome.
Version 103.0.5060.134

MS Edge Chrominum.
Version 104.0.1293.47
