### ISSUE TITLE
Impersonate

### ISSUE THREAD

**Issue by enzoporcasi** [rajyraman/Levelup-for-Dynamics-CRM#210]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
    Extension Version: 3.5.8
    ----------------------------------------------------------
    Hi, 
i'm trying to use the impersonate function but I can see only a subset of user. in my system i have got about two thousand of user, and I cann see only the some hundreds.

how can I solve?
regards
Enzo

**Comment by rajyraman** [comment]
@enzoporcasi - Pushed out new release over the weekend. Please check with v3.6.0. It should retrieve more than 5000 users. There is no search yet though.
