### ISSUE TITLE
All Level up features are disabled if MCAS is enabled

### ISSUE THREAD

**Issue by kermaperuna** [rajyraman/Levelup-for-Dynamics-CRM#214]
None of the Level Up buttons work if D365 environment has Microsoft Cloud App Security (MCAS) enabled. Tested in two different tenants with multiple users / devices. Having used to the tool it would be such a life-saver to get the features working also in MCAS enabled environments.

**Comment by rajyraman** [comment]
@kermaperuna - This is the first time I am hearing about this. Based on my Googling it seems that it is related to Defender for Cloud Apps. Can you check the browser console and see if you can see any errors? I am think it might be something to do with CSP rules that prevent JavaScript from being injected into the page.

**Comment by kermaperuna** [comment]
@rajyraman - With quick testing I wasn't able to notice any errors during the page load process or when triggering Level Up functions from the drop-down menu. The extension seems to be loading up properly so that all Level Up functions are visible but once clicking any of the function buttons nothing seems to be happening in UI or the console side.

**Comment by J76786786** [comment]
This sounds like a good way of blocking Level up if needed. Referring to all Requirements where Users get too creative and bypasses UI.

**Comment by rajyraman** [comment]
@kermaperuna - This is a bug which I have fixed in the latest release. Impersonation will not work with MCAS, but rest should work.
