### ISSUE TITLE
Impersonation is not working

### ISSUE THREAD

**Issue by KBaileyHS** [rajyraman/Levelup-for-Dynamics-CRM#217]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
    Extension Version: 3.5.9
    ----------------------------------------------------------
When I attempt to impersonate a user, I find the user in the drop down list and choose them then slide the button to start the impersonation. The Dynamics screen would normally refresh and the the impersonation would be on. Now I'm not getting that auto refresh and the impersonation never happens

**Comment by rajyraman** [comment]
@KBaileyHS  - Pushed out new release over the weekend. Please check with v3.6.0
