### ISSUE TITLE
Impersonate is not working

### ISSUE THREAD

**Issue by ebruklcarslan** [rajyraman/Levelup-for-Dynamics-CRM#218]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
    Extension Version: 3.5.9
    ----------------------------------------------------------
    [DESCRIBE ISSUE HERE]

Impersonate is not working
![2022-09-16_15-56-04](https://user-images.githubusercontent.com/113695463/190643919-c703ec17-7dc3-42fe-88d5-6cfabf3b2cb9.png)

**Comment by rajyraman** [comment]
@ebruklcarslan - Pushed out new release over the weekend. Please check with v3.6.0

**Comment by nja12** [comment]
@rajyraman Appear to still be an issue:

![image](https://user-images.githubusercontent.com/5009566/195221401-ad2809f3-51f4-474e-904f-0bab8ee031e5.png)

**Comment by rajyraman** [comment]
@nja12 - Do have any environment where you can screen share this issue? I still cannot repro it

**Comment by Dokalfares** [comment]
I have the same problem in some tenants, it doesen't works on USA enviroments, but it works well on Europe

**Comment by GerritRega** [comment]
looks like this -- > https://github.com/rajyraman/Levelup-for-Dynamics-CRM/issues/216
