### ISSUE TITLE
I'm not able to get impersonate working

### ISSUE THREAD

**Issue by Ian-O** [rajyraman/Levelup-for-Dynamics-CRM#219]
*Desktop (please complete the following information):**
 - Browser [e.g. Chrome, Firefox, Edge Chromium]
 - Dynamics 365/Power Apps Version
 - Admin/Non-admin
 - Online/On-Premise
 - Unified Inferface/Classic Interface
 - Model Driven App/Classic App
 - Entity name, if it is an out-of-the-box entity

**Desktop (please complete the following information):**
 - Chrome Version 105.0.5195.102 (Official Build) (64-bit) 
 -- InPrivate and normal
 - Edge Chromium Version 105.0.1343.33 (Official build) (64-bit)
 -- normal
 - Dynamics 365
 - I'm an admin attempting to impersonate a Non-admin
 - Online
 - Unified Inferface
 - Model Driven App
 - Entity name: any entity

**To Reproduce**
1. Go to Level Up 
2. Click on Impersonate
3. Scroll down to selected User
4. The initials of the user do display on the levelup icon, the browser does not refresh.
5. CE isn't running using the impersonated User its running as previous user/logged in user.

**Comment by rajyraman** [comment]
@Ian-O - Pushed out new release over the weekend. Please check with v3.6.0
