### ISSUE TITLE
Impersonation not working

### ISSUE THREAD

**Issue by CLassen21** [rajyraman/Levelup-for-Dynamics-CRM#220]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.50
    Extension Version: 3.5.8
    ----------------------------------------------------------
When trying to impersonate a user by choosing from the dropdown list and toggle on, nothing happens except it will show the users initials on the level up logo.

**Comment by rajyraman** [comment]
@Ian-O - Pushed out new release over the weekend. Please check with v3.6.0

**Comment by richardwgtca** [comment]
Impersonation is still not working. User list is empty.

**Comment by GerritRega** [comment]
looks like this -- > https://github.com/rajyraman/Levelup-for-Dynamics-CRM/issues/216
