### ISSUE TITLE
Impersonate option is not working on Levelup for dynamics/power platform

### ISSUE THREAD

**Issue by SU8234** [rajyraman/Levelup-for-Dynamics-CRM#225]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
    Extension Version: 3.6.0
    ----------------------------------------------------------
    [DESCRIBE ISSUE HERE]

**Comment by SU8234** [comment]
we are using v 3.6.0, but still not bale to see users in Imperonation list.

**Comment by vebivar** [comment]
Same here, since updated to 3.6, the impersonation stopped working.
Version
3.6.0
Updated
October 8, 2022

**Comment by GerritRega** [comment]
looks like this -- > https://github.com/rajyraman/Levelup-for-Dynamics-CRM/issues/216
