### ISSUE TITLE
add Button to enable Command Checker

### ISSUE THREAD

**Issue by Painy187** [rajyraman/Levelup-for-Dynamics-CRM#228]
In CRM and in the Level Up Extension there is currently no easy way to enable the Command Checker.
Each time you have to append silly text to the url, whcih i never can remember... So each time i have to open a bookmark, copy the text and then append it to the url... But should be easy for Level Up to make that on click of a button (maybe in Navigation tab).

Text that nmeed to be added to url: &flags=FCB.CommandChecker=true&ribbondebug=true

More information on Command Checker can be found here:
d365demystified.com/2020/04/14/debug-ribbon-button-customization-using-command-checker-in-dynamics-365-ce-unified-interface/

**Comment by BetimBeja** [comment]
Hi @Painy187 ,
as @phuocle said this functionality is already there.
Please follow these steps:
1 - Open the `Admin Area` menu 
<img width="531" alt="image" src="https://user-images.githubusercontent.com/11160171/197116415-816585c4-2d6f-407c-8dfe-6e0621c0ae4e.png">
2 - Choose the `Command Debugger` menu 
<img width="526" alt="image" src="https://user-images.githubusercontent.com/11160171/197116548-c24ce4c0-1f21-49ae-8e4f-4fcc71b3aef5.png">
