### ISSUE TITLE
Impressionate is not loading users

### ISSUE THREAD

**Issue by MarceloBassi** [rajyraman/Levelup-for-Dynamics-CRM#229]
Browser Version: 5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
    Extension Version: 3.6.0
    ----------------------------------------------------------
    When i Try to impressionate an user I don´t get the user´s list

![image](https://user-images.githubusercontent.com/69473879/198276487-27e02a90-2370-4423-b6f8-4ba3cebc9e13.png)

**Comment by MTruocchio** [comment]
Same Issue here

**Comment by GerritRega** [comment]
looks like this -- > https://github.com/rajyraman/Levelup-for-Dynamics-CRM/issues/216
