### ISSUE TITLE
Clicking Logical Names again doesn't show the normal names

### ISSUE THREAD

**Issue by VParshu** [rajyraman/Levelup-for-Dynamics-CRM#23]
Hi Natraj,
<br />
<br />I think toggling Logical Names button should show again the previous display names. Clicking Logical Names button once shows correctly the underlying schema name; but clicking again the schema names are repeated and it fills up the screen. Can you give a toggle button or something like that.
<br />
<br />Still awesome work done though !!!  Thank you,
<br />
<br />- Prashant

**Comment by rajyraman** [comment]
I'll try to hide the button if it has been clicked once already for the form.

**Comment by VParshu** [comment]
Natraj,
What I think will be better solution is to make it toggle. Like if we click it once; it will show schema names. Then the label on the button will change to 'Show Normal names'; and clicking that will show again the normal names.
That just came in my mind. If its not that simple and time consuming then its ok. 
Its up to you Natraj. :+1: 

-Prashant

**Comment by rajyraman** [comment]
Partially fixed in v1.9. Clicking the button multiple times will not duplicate the text boxes.
