### ISSUE TITLE
Not able to impersonate as dynamics user with level up

### ISSUE THREAD

**Issue by SilviaRabionet** [rajyraman/Levelup-for-Dynamics-CRM#230]
I am using level up to imperosnate as user. this has previously work but not for the last couple of weeks. When trying to impersonate it shows a blank picklist , i can not select any user.

    Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
    Extension Version: 3.6.0
    ----------------------------------------------------------
    [DESCRIBE ISSUE HERE]

**Comment by GerritRega** [comment]
looks like this -- > https://github.com/rajyraman/Levelup-for-Dynamics-CRM/issues/216
