### ISSUE TITLE
Users not listed in Impersonate list

### ISSUE THREAD

**Issue by tjnielsen3** [rajyraman/Levelup-for-Dynamics-CRM#232]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
    Extension Version: 3.6.0
    ----------------------------------------------------------
    Not all users are listed in the drop down list.

**Comment by GerritRega** [comment]
looks like this -- > https://github.com/rajyraman/Levelup-for-Dynamics-CRM/issues/216
