### ISSUE TITLE
Impersonate Not working

### ISSUE THREAD

**Issue by jacr777** [rajyraman/Levelup-for-Dynamics-CRM#233]
Browser Version: 5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
    Extension Version: 3.6.0
    ----------------------------------------------------------
    [DESCRIBE ISSUE HERE]
For some reason impersonate stop working a few weeks ago, is this a known bug??

**Comment by rabyjrm** [comment]
Same issue here. Previously we were able to run it using Edge or Chrome.

**Comment by GerritRega** [comment]
do you mean this behavior ? -- > https://github.com/rajyraman/Levelup-for-Dynamics-CRM/issues/216
