### ISSUE TITLE
Impersonation is not working. 

### ISSUE THREAD

**Issue by tiemar** [rajyraman/Levelup-for-Dynamics-CRM#235]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
    Extension Version: 3.6.0
    ----------------------------------------------------------
   It seems only on instances where the user count is quite high. 
   Instances with less users work fine. 
   Usercount is 9300 !
   
   CrashReport:
		FileName:/scripts/levelup.extension.js
		LineNumber:1966
		Function:
		ErrorReport:<CrmScriptErrorReport>
  <ReportVersion>1.0</ReportVersion>
   <OriginContext></OriginContext>
   <OriginCorrelationId>undefined</OriginCorrelationId>
  <ScriptErrorDetails>
   <Message>Uncaught TypeError&#58; Cannot read properties of null &#40;reading &#39;1&#39;&#41;</Message>
   <Line>1966</Line>
   <URL>&#47;scripts&#47;levelup.extension.js&#63;ver&#61;1549003435</URL>
   <PageURL>&#47;main.aspx&#63;settingsonly&#61;true&#35;390053808</PageURL>
   <Function></Function>
   <FunctionRaw></FunctionRaw>
   <SourceScriptName></SourceScriptName>
   <CallStack>
TypeError&#58; Cannot read properties of null &#40;reading &#39;1&#39;&#41;&#10;    at f &#40;chrome-extension&#58;&#47;&#47;bjnkkhimoaclnddigpphpgkfgeggokam&#47;scripts&#47;levelup.extension.js&#58;1966&#58;2474&#41;&#10;    at s.onload &#40;chrome-extension&#58;&#47;&#47;bjnkkhimoaclnddigpphpgkfgeggokam&#47;scripts&#47;levelup.extension.js&#58;1966&#58;3672&#41;   </CallStack>
  </ScriptErrorDetails>
  <ClientInformation>
   <BrowserUserAgent>Mozilla&#47;5.0 &#40;Windows NT 10.0&#59; Win64&#59; x64&#41; AppleWebKit&#47;537.36 &#40;KHTML, like Gecko&#41; Chrome&#47;107.0.0.0 Safari&#47;537.36</BrowserUserAgent>
   <BrowserLanguage>undefined</BrowserLanguage>
   <SystemLanguage>undefined</SystemLanguage>
   <UserLanguage>undefined</UserLanguage>
   <ScreenResolution>1920x1080</ScreenResolution>
   <ClientName>Web</ClientName>
   <ClienState>Online</ClienState>
   <ClientTime>2022-11-15T10&#58;27&#58;57</ClientTime>
  </ClientInformation>
</CrmScriptErrorReport>

**Comment by GerritRega** [comment]
looks like this -- > https://github.com/rajyraman/Levelup-for-Dynamics-CRM/issues/216
