### ISSUE TITLE
Impersonate not working

### ISSUE THREAD

**Issue by albertobelardi** [rajyraman/Levelup-for-Dynamics-CRM#238]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
    Extension Version: 3.6.0
    ----------------------------------------------------------
Hi, the list of users to imperonate is emty, coult you fix please? Thank you.

![image](https://user-images.githubusercontent.com/25862755/202491731-576f91c0-aefd-4fa3-89a7-c7950006726b.png)

**Comment by GerritRega** [comment]
looks like this -- > https://github.com/rajyraman/Levelup-for-Dynamics-CRM/issues/216
