### ISSUE TITLE
Bug with Impersonate

### ISSUE THREAD

**Issue by romeusantiago** [rajyraman/Levelup-for-Dynamics-CRM#241]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.56
    Extension Version: 3.6.0
    ----------------------------------------------------------
    Hi.
    
    I'm trying to use the "Impersonate" but when I click and try to find the "User to impersonate", Level Up doesn't load the users on my environment.
    
    Can you help me?
    
    Check the screen below.
    
    Tks in advance and my best regards.
    
![image](https://user-images.githubusercontent.com/15317054/204806302-4aca81dd-6ed7-46c8-9015-f9feac586407.png)

**Comment by GerritRega** [comment]
looks like this -- > https://github.com/rajyraman/Levelup-for-Dynamics-CRM/issues/216
