### ISSUE TITLE
Impersonate

### ISSUE THREAD

**Issue by SilviaRabionet** [rajyraman/Levelup-for-Dynamics-CRM#245]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
    Extension Version: 3.6.0
    ----------------------------------------------------------
   Impersonate function is not working. When I select impersonate I dont see any users in the drop down list. I am a system admin and has got this working in the past.

<img width="524" alt="image" src="https://user-images.githubusercontent.com/115151854/206676609-86a797d4-b544-407c-81b2-4c57dfbe96a9.png">

**Comment by GerritRega** [comment]
looks like this -- > https://github.com/rajyraman/Levelup-for-Dynamics-CRM/issues/216
