### ISSUE TITLE
Impersonate not showing list of users

### ISSUE THREAD

**Issue by cdjefferson** [rajyraman/Levelup-for-Dynamics-CRM#249]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
    Extension Version: 3.6.0
    ----------------------------------------------------------
    [DESCRIBE ISSUE HERE]

When attempting to impersonate a user, the list shows a small black box and no users are available for selection.

![Capture](https://user-images.githubusercontent.com/123729521/215053010-bb08a4f4-6b06-4e0e-9bbf-7b4b1b45b1a2.PNG)

**Comment by GerritRega** [comment]
--> https://github.com/rajyraman/Levelup-for-Dynamics-CRM/issues/216
