### ISSUE TITLE
Impersonate function no longer working

### ISSUE THREAD

**Issue by pdxandpvr** [rajyraman/Levelup-for-Dynamics-CRM#250]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.70
    Extension Version: 3.6.0
    ----------------------------------------------------------
Impersonate functionality no longer works

**Comment by GerritRega** [comment]
https://github.com/rajyraman/Levelup-for-Dynamics-CRM/issues/216
