### ISSUE TITLE
Does not work in latest Edge version

### ISSUE THREAD

**Issue by aaronric** [rajyraman/Levelup-for-Dynamics-CRM#253]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.57
    Extension Version: 3.6.0
    ----------------------------------------------------------
   Edge was recently updated and this no longer works. It does not load in the toolbar unless you disable and re-enable. When you do that, it opens up but when clicking on any button, nothing happens

**Comment by myrlj** [comment]
and chrome ^

**Comment by rajyraman** [comment]
@aaronric - Please see #254. I am working on it.
