### ISSUE TITLE
Extension is not working. It opens up but when clicking on any button, nothing happens.

### ISSUE THREAD

**Issue by shweta0310** [rajyraman/Levelup-for-Dynamics-CRM#254]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.0.0
    Extension Version: 3.6.0
    ----------------------------------------------------------
    [DESCRIBE ISSUE HERE]

**Comment by brettofthewild** [comment]
Having this same issue for the past couple of days. Just straight up not working at all.

**Comment by nmayeur** [comment]
Hi, same issue, levelup is not working on crm12. Colleagues told me it was still working on crm4, but not on crm3.
Thank you for your help.

**Comment by thibaug** [comment]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.63
Extension Version: 3.6.0

Hi, I'm having issues as well this morning. Interestingly, it kinda works if I'm in Settings (I see the menu for the Extension), but not if in on a CRM App. I'm getting the extension menu instead. It's like the URL is not recognized as CRM. I'm in CRM3.

Thanks!

**Comment by Bungeetaco** [comment]
Also seeing the same issue in Brave, Firefox and Edge. In Brave, the extension menu appears instead of the LevelUp menu. In Firefox, the icon becomes grayed out when trying to click on it while browsing a CRM window:

![image](https://user-images.githubusercontent.com/5958682/223190398-33e146fa-018c-442e-a988-f5273c99b7cc.png)
![image](https://user-images.githubusercontent.com/5958682/223190590-1f102879-31cf-4456-a810-f92fb3872747.png)

**Comment by Bhawk90** [comment]
Most probably the latest update of Power Platform is causing the issue. We already have version 9.2.23023.00158 installed in many of our environments and it has broken Levelup for Dynamics, we cannot use it. On other environments with older versions, there are no issues.

Please refer to the pull request I have already posted. https://github.com/rajyraman/Levelup-for-Dynamics-CRM/pull/257

Could you please confirm (if you have access to the Power Platform admin center) if you are on the latest version?

**Comment by Bhawk90** [comment]
Hello Bungeetaco,

Thanks for the reply! Microsoft seems to have changed the script structure a bit in the latest version and that is causing the issue. Try to clone the source from the branch I have posted, then you should be able to build it by first running `npm install`, then `npm run dev:edge` or `npm run dev:chrome` matching your browser.

If you are running Edge (probably this is the same in Chrome), you can follow [this](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/extension-sideloading) guide on how you can sideload the extension. You should pick the folder found in the `dist` folder, either edge or chrome.

**Comment by cseguin7i** [comment]
Hello @Bungeetaco & @Bhawk90 

We are having the same issue.

Tried on these browsers: 
Edge Version 110.0.1587.63 (Official build) (64-bit)
Chrome Version 110.0.5481.178 (Official Build) **(64-bit)**

On this Power Platform database version: 9.2.23023.00158

![image](https://user-images.githubusercontent.com/127140307/223197543-a2cda6f6-6cc1-4361-ab19-4f8fcd198c50.png)

**Comment by Bungeetaco** [comment]
> Hello Bungeetaco,
> 
> Thanks for the reply! Microsoft seems to have changed the script structure a bit in the latest version and that is causing the issue. Try to clone the source from the branch I have posted, then you should be able to build it by first running `npm install`, then `npm run dev:edge` or `npm run dev:chrome` matching your browser.
> 
> If you are running Edge (probably this is the same in Chrome), you can follow [this](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/extension-sideloading) guide on how you can sideload the extension. You should pick the folder found in the `dist` folder, either edge or chrome.

Hi Bhawk,

I was able to build the extension using your instructions after installing gulp and running the command inside Git Bash using `export NODE_OPTIONS=--openssl-legacy-provider`.  A huge thank you for taking the time to provide build instructions! 

Seems like @rajyraman should be able to merge the pull request, pack it and re-sign the extension for distribution if they approve the pull after reviewing. I'll sign the extension myself for the time being and distribute it to my team until that happens.

Let me know if I can send you a tip for a coffee or something :)

**Comment by Bhawk90** [comment]
Hi Bungeetaco,

I am happy that I could help! A lot of my colleagues and friends are using the tool as well so I can understand the frustration the issue might have caused :) Let's hope the pull request will be accepted soon and the situation will be resolved for all!

**Comment by rajyraman** [comment]
@Bhawk90 @Bungeetaco - I started working on the extension last week to work on so many tickets raised on the impersonate function, update manifest to v3, update obsolete npm packages, and issues with using with Defender for Web Apps. I didn't realise this was happening. I looked at the PR. I need to figure out if there is a way to get this working without constantly update the extension code if Microsoft changes the code on their side.

**Comment by Bungeetaco** [comment]
> @Bhawk90 @Bungeetaco - I started working on the extension last week to work on so many tickets raised on the impersonate function, update manifest to v3, update obsolete npm packages, and issues with using with Defender for Web Apps. I didn't realise this was happening. I looked at the PR. I need to figure out if there is a way to get this working without constantly update the extension code if Microsoft changes the code on their side.

Hi Rajyraman,

Thank you very much for maintaining this extension and for continuing to improve on it. It really does make my work a lot easier.

**Comment by Bhawk90** [comment]
> @Bhawk90 @Bungeetaco - I started working on the extension last week to work on so many tickets raised on the impersonate function, update manifest to v3, update obsolete npm packages, and issues with using with Defender for Web Apps. I didn't realise this was happening. I looked at the PR. I need to figure out if there is a way to get this working without constantly update the extension code if Microsoft changes the code on their side.

Thank you Rajyraman, I really appreciate it. It really is a pain to do lots of tasks inside Power Platform without your extension :) 

I am on the side of finding a permanent solution for the issue as well (I was wondering if you could rely on the availibility of the Xrm object?), however - just out of curiosity - would it be possible to release a quick fix for the issue until the final fix is ready?

Thank you again and huge respect for the time and effort you have put into this project!!

**Comment by eogabriel** [comment]
Hello @Bhawk90, is there anything I can do, like a temporary workaround, to fix this issue without having to update it? The reason I'm asking is because my computer has restrictions on what I can download and install. Many thanks.

**Comment by Bhawk90** [comment]
Hello @eogabriel! Sadly, an update must be released and installed for the issue to be fixed. Apart from that, building and sideloading an updated version of the extension might be a temporary workaround as well, but I'm not sure that this would be possible in your scenario, because of the restrictions you have on your computer.

**Comment by rajyraman** [comment]
I have submitted v3.6.2 for review in Chrome Web Store. There are whole bunch of changes around impersonation logic due to v3 manifest, leading to new permissions. This might take additional time for Google to review and approve.

**Comment by irah2008** [comment]
@rajyraman  I can see the chrome webstore is updated with newer version. Any idea on the edge webstore? as Edge still shows older version.
