### ISSUE TITLE
Nothing happens no matter what button I press

### ISSUE THREAD

**Issue by Dallie04** [rajyraman/Levelup-for-Dynamics-CRM#258]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.63
    Extension Version: 3.6.0
    ----------------------------------------------------------
I use Edge

At the beginning, brought me the link to add the extension. Delete, put back and there opens the level up buttons window but if I click on any button, nothing happens.

**Comment by rajyraman** [comment]
@Dallie04 - Please see #254. I am working on it.
