### ISSUE TITLE
Level Up not opening

### ISSUE THREAD

**Issue by blizli24** [rajyraman/Levelup-for-Dynamics-CRM#260]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
    Extension Version: 3.6.0
    ----------------------------------------------------------
    When I click on the extension I get number of options to click as remove from chrome, unpin etc. , but not the usual options and when checking the inspect popup I read this error message
<img width="655" alt="image" src="https://user-images.githubusercontent.com/58257558/223375936-7f354afd-ba99-4f31-991c-7529c90259c1.png">

**Comment by rajyraman** [comment]
@blizli24 - Please see #254. I am working on it.
