### ISSUE TITLE
Level Up dead ? 

### ISSUE THREAD

**Issue by ciro-escola** [rajyraman/Levelup-for-Dynamics-CRM#261]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
    Extension Version: 3.6.0
    ----------------------------------------------------------
    [DESCRIBE ISSUE HERE]

**Comment by rajyraman** [comment]
@ciro-escola- Please see #254. I am working on it.
