### ISSUE TITLE
Level up for Dynamics 365/Power Apps

### ISSUE THREAD

**Issue by kmpcan** [rajyraman/Levelup-for-Dynamics-CRM#262]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
    Extension Version: 3.6.0
    ----------------------------------------------------------
    [DESCRIBE ISSUE HERE]

the app has stopped working for Chrome and edge both. Please advise asap.

**Comment by rajyraman** [comment]
@kmpcan - Please see #254. I am working on it.
