### ISSUE TITLE
Impersonating via account name

### ISSUE THREAD

**Issue by Bl4ckscream** [rajyraman/Levelup-for-Dynamics-CRM#268]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.63
    Extension Version: 3.6.2
    ----------------------------------------------------------
  
With the newest extension update (3.6.2) it is unfortunately no longer possible to quickly impersonate different users via name search within the "Impersonate" tab as there is no drop-down menu and the full account name is always required. 
As someone who has to impersonate many users on a daily basis, this makes work a lot harder.

**Comment by rajyraman** [comment]
@Bl4ckscream - This is just a stop gap because I had to push out this release due to the bug fix. In the next version there will be a search and select capability. Please see https://github.com/rajyraman/Levelup-for-Dynamics-CRM/issues/266#issuecomment-1464808380
