### ISSUE TITLE
Impersonation Issue

### ISSUE THREAD

**Issue by rmantei23** [rajyraman/Levelup-for-Dynamics-CRM#270]
Browser Version: [object Navigator]
    Extension Version: 3.6.2
    ----------------------------------------------------------
When I try to impersonate a user in the D365 CRM environment, I am no longer select from a list. The button shows, "reset impersonation" but that is all I am getting. I tried restarting my system but I am still getting an error. My other colleague is getting the issue as well.
![image](https://user-images.githubusercontent.com/127896438/225129621-20f497a8-d41c-4f54-a2b5-db38fba8ee09.png)

**Comment by rajyraman** [comment]
@rmantei23 - This is just a stop gap because I had to push out this release due to the bug fix. In the next version there will be a search and select capability. Please see https://github.com/rajyraman/Levelup-for-Dynamics-CRM/issues/266#issuecomment-1464808380

**Comment by rajyraman** [comment]
@rmantei23 - If possible you can sideload the extension from https://github.com/rajyraman/Levelup-for-Dynamics-CRM/releases/tag/v3.6.3 before I submit this version to Chrome and Edge stores.

**Comment by rmantei23** [comment]
Awesome. Do you know when the next push will be?

Rachel Mantei
Associate Developer
New Dynamic, LLC
10561 Barkley Street, Suite 601, Overland Park, KS  66212
CELL (417) 496-6513  |  OFFICE  (913) 402-4599
***@***.******@***.***>|  www.newdynamicllc.com<http://www.newdynamicllc.com/>

This e-mail is intended solely for the person or entity to which it is addressed and may contain confidential and/or privileged information. Any review, dissemination, copying, or other use of this e-mail by persons or entities other than the addressee is prohibited. If you have received this e-mail in error, please contact the sender immediately and delete the material from any computer.

***@***.***

**Comment by rajyraman** [comment]
@rmantei23 - The new version is live in Chrome. Edge might take couple of days more.
