### ISSUE TITLE
LevelUp Not working in latest Firefox update

### ISSUE THREAD

**Issue by SalesGreyMonkey** [rajyraman/Levelup-for-Dynamics-CRM#271]
Browser Version: 5.0 (Windows)
    Extension Version: 3.5.5
    ----------------------------------------------------------
Hello

You may already know this but the latest update to Firefox 111.0 (64-bit) has caused Level Up to stop working. The extension icon is not clickable within Dynamics. It however, does work when on non-Dynamics websites.

I use this within Firefox Multi-Account Containers.

![image](https://user-images.githubusercontent.com/128041224/225589677-08ba70d0-cc4f-4e32-801c-fba14361f755.png)

Many thanks

**Comment by rajyraman** [comment]
Tracking on #276
