### ISSUE TITLE
Impersonation Not Working

### ISSUE THREAD

**Issue by seeryc** [rajyraman/Levelup-for-Dynamics-CRM#272]
Browser Version: Chrome 111.0.5563.65 (64-bit)
    Extension Version: 3.6.2
    ----------------------------------------------------------
    Impersonation is no longer working. Instead of a drop-down, I am forced to type the user's email address but even after doing this (ensuring the email address is valid), the impersonation feature does not work.

**Comment by DanThoor** [comment]
Same here. I am running on an just updated Win 11 PC with the latest Chrome: Version 111.0.5563.65 (Official Build) (64-bit)

**Comment by rajyraman** [comment]
@seeryc @DanThoor - That was a stop gap UI to push out the bug fix release. v3.6.3 has search capability. Please see https://github.com/rajyraman/Levelup-for-Dynamics-CRM#impersonating-another-user
