### ISSUE TITLE
Level up for Dynamics 365 not working for Firefox browser 

### ISSUE THREAD

**Issue by kalinskata** [rajyraman/Levelup-for-Dynamics-CRM#276]
Browser Version: 5.0 (Windows)
    Extension Version: 3.5.5
    ----------------------------------------------------------
   I found out that my Level up browser extension is not working on Firefox browser this morning. I also read that this issue is fixed for Chrome and Edge already could you cooperate to fix it and for Firefox.

![firefox_D4EWpeWdEZ](https://user-images.githubusercontent.com/128365856/226300278-f6ecb737-3f0b-475b-ad49-c75fd1c8e8eb.png)

**Comment by kalinskata** [comment]
Hi there, it's really critical for us. Is there any chance to be fixed for Firefox because Edge and Chrome are managed by our organization and we could not use it in the browser that you already fixed it. If the information is insufficient do not hesitate to contact, I'll try to cooperate as much as I can. Thanks a lot for your efforts in advance.

**Comment by rajyraman** [comment]
The issue is that Firefox does not support declarativeNetRequest permission in v3 manifest. So when I released the fix last week I could not include Firefox. I have to remove Impersonation and release a different version for Firefox.

**Comment by stevhk** [comment]
Hi @rajyraman is there any good news regarding to this issue?

**Comment by rajyraman** [comment]
I have uploaded the earlier version based on v2 manifest to Firefox store. There seems to be issues getting this v3 manifest working in Firefox, so I am removing impersonation and sticking with v2 manifest only for Firefox.

![image](https://user-images.githubusercontent.com/5035266/236596556-f7666cba-2a62-410f-a61d-aa37ff474d62.png)

**Comment by rajyraman** [comment]
Extension is now live.

@stevhk @NC-OGH @kalinskata @lfalck 

https://addons.mozilla.org/en-US/firefox/addon/level-up-for-d365-power-apps/

**Comment by stevhk** [comment]
> Version with fix is now live.
> 
> @stevhk @NC-OGH @kalinskata @lfalck
> 
> https://addons.mozilla.org/en-US/firefox/addon/level-up-for-d365-power-apps/

Thanks @rajyraman for the update
