### ISSUE TITLE
V1.9 Beta - Forms area seems to be missing.

### ISSUE THREAD

**Issue by htimsm87** [rajyraman/Levelup-for-Dynamics-CRM#28]
I have V1.9 Beta installed and the Forms area seems to be missing.  When I click on the extension it starts with Navigation.

**Comment by MattFromGer** [comment]
Why did you close your issue without a comment?
I'm having the same problem. How did you solve it?

**Comment by rajyraman** [comment]
Forms area appears only when you open a form. If you updated the extension, try refreshing the tab.

**Comment by MattFromGer** [comment]
Ah thanks for the clarification!
I've tried to use it on a dashboard, seems like not all features are available there.

**Comment by rajyraman** [comment]
I hid irrelevant areas depending on the current context, to close #17
