### ISSUE TITLE
Tab refreshes when trying to impersonate user

### ISSUE THREAD

**Issue by frederikkehlet** [rajyraman/Levelup-for-Dynamics-CRM#283]
Browser Version: [object Navigator]
    Extension Version: 3.6.3
    ----------------------------------------------------------
    The tab refreshed when I try to search for a user to impersonate.

**Comment by rajyraman** [comment]
@frederikkehlet - This seems to happen when there is exactly one result returned. This reload should have impersonated that one single user. As a workaround maybe just alter your search so that multiple results are returned, and you can choose a user. I will fix it in the next version.

**Comment by rajyraman** [comment]
@frederikkehlet - Tracking on #280
