### ISSUE TITLE
Impersonate user button remains greyed out

### ISSUE THREAD

**Issue by eduarddalm** [rajyraman/Levelup-for-Dynamics-CRM#286]
Browser Version: [object Navigator]
    Extension Version: 3.6.3
    ----------------------------------------------------------
    [DESCRIBE ISSUE HERE]
    
![2023-03-26 10_53_41-Window](https://user-images.githubusercontent.com/25723165/227765458-caf79869-88ee-4c15-aff2-b4f9cd402825.png)

**Comment by rajyraman** [comment]
@eduarddalm - Might be related to #280. I am keeping this open for now. I submitted new release v3.6.4 in Edge and Chrome. You can try side loading this release and see if that fixes your issue https://github.com/rajyraman/Levelup-for-Dynamics-CRM/releases/tag/v3.6.4

**Comment by rajyraman** [comment]
@eduarddalm - The new version is live. Please check if that resolves your issue.

https://chrome.google.com/webstore/detail/level-up-for-dynamics-365/bjnkkhimoaclnddigpphpgkfgeggokam?hl=en
