### ISSUE TITLE
Stopped working on Firefox

### ISSUE THREAD

**Issue by Yiogi1** [rajyraman/Levelup-for-Dynamics-CRM#289]
Browser Version: 5.0 (Windows)
    Extension Version: 3.5.5
    ----------------------------------------------------------
    It suddenly started being disabled in CRM tabs, and enabled in most other non-CRM tabs. it's as if the logic is somehow inverted. 
![image](https://user-images.githubusercontent.com/64966512/228840274-4a920f6c-8b37-415a-954c-e07387d8836e.png)

**Comment by NoelArn** [comment]
I have the same problem. If i go to the settings inside of dynamics it's not disabled but as soon as i switch back its disabled again.

**Comment by rajyraman** [comment]
Tracking in #276.
