### ISSUE TITLE
[BUG]: Nothing works - unresponsive clicks - menu greyed out

### ISSUE THREAD

**Issue by cseabolt84** [rajyraman/Levelup-for-Dynamics-CRM#293]
Hello,

Ths doesn't seem to work at all.  When I click ANY option, nothing happens; when I click into the side menu, everything is greyed out. I'm trying to use this to view the optionset values of our CRM.

**Desktop (please complete the following information):**
 - Browser Chrome
 - Dynamics 365/Power Apps Version
 - Non-admin
 - Online/On-Premise: online

**Comment by rajyraman** [comment]
@cseabolt84 - Can you please post screenshot or short video? Please also check in the devtools console to see if there are any errors. I am not experiencing this issue in crm6. Which region is your instance in?

**Comment by cseabolt84** [comment]
Hello,

We can close this ticket.  I’m not sure what has happened, but the issue resolved itself today.

[Icon  Description automatically generated]

Chris Seabolt
IT Business Partner
C: 202.445.3717  |  sonesta.com<http://www.sonesta.com/>
***@***.***  ***@***.***   ***@***.***   ***@***.***


From: Natraj Yegnaraman ***@***.***>
Sent: Wednesday, June 28, 2023 3:51 AM
To: rajyraman/Levelup-for-Dynamics-CRM ***@***.***>
Cc: Seabolt, Chris ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [rajyraman/Levelup-for-Dynamics-CRM] [BUG]: Nothing works - unresponsive clicks - menu greyed out (Issue #293)


@cseabolt84 [github.com]<https://urldefense.com/v3/__https:/github.com/cseabolt84__;!!BRo2-Ji4!xs6So5OJJoo2_84cLGXOLBltmrRAS2r-yw3zLq91iBkrNmAP3sdSHoDHUhRBdzvJqr58jp6xw0ZXczXDBMvA9TEj79Y$> - Can you please post screenshot or short video? Please also check in the devtools console to see if there are any errors. I am not experiencing this issue in crm6. Which region is your instance in?
