### ISSUE TITLE
[BUG]: I am unable to click on anything. Just downloaded the extension.

### ISSUE THREAD

**Issue by mcgratwb** [rajyraman/Levelup-for-Dynamics-CRM#294]
**Describe the bug**

**Desktop (please complete the following information):**
 - Browser [e.g. Chrome, Firefox, Edge Chromium]
 - Dynamics 365/Power Apps Version
 - Admin/Non-admin
 - Online/On-Premise
 - Unified Interface/Classic Interface
 - Model Driven App/Classic App
 - Entity name, if it is an out-of-the-box entity

**To Reproduce**

**Expected behavior**

**Screenshots**

**Videos**
If possible, attach a screen recording with sensitive and PII information blurred out.

**Additional context**
Add any other context about the problem here. e.g. browser Dev  Tools output

**Comment by rajyraman** [comment]
Tracking in #293
