### ISSUE TITLE
[BUG]: There is no IMPERSONATE tab when using FireFox browse

### ISSUE THREAD

**Issue by Andrii338** [rajyraman/Levelup-for-Dynamics-CRM#295]
How to add this tab?
![изображение](https://github.com/rajyraman/Levelup-for-Dynamics-CRM/assets/104854086/b3379441-8251-4222-b9c1-614a5c80b099)

**Comment by rajyraman** [comment]
@Andrii338 - Please see https://github.com/rajyraman/Levelup-for-Dynamics-CRM/issues/276#issuecomment-1481952918

Firefox does not support parts of v3 manifest, so I had to drop this on Firefox.
