### ISSUE TITLE
[BUG]: Build is failed

### ISSUE THREAD

**Issue by drperstry** [rajyraman/Levelup-for-Dynamics-CRM#305]
**Describe the bug**
When I try to build the project, built scripts are created but corrupted, after updating webpack and ts-loader, it is building and says the chunks are emitted but when I check the /dist/scripts folder I dont find files except of third party libraries.

**To Reproduce**
1. npm i
2. npm run dev
3. error in screenshot 1
4. npm i ts-loader@latest webpack@latest
5. npm run dev
6. error in screenshot 2

**Expected behavior**
it should output all chunks and running fine when loaded into chrome extensions.

**Screenshots**
Issue 1:
![image](https://github.com/rajyraman/Levelup-for-Dynamics-CRM/assets/71937375/de75e07b-1be5-4c02-87e7-69223f48f2ce)

Issue 2:
![image](https://github.com/rajyraman/Levelup-for-Dynamics-CRM/assets/71937375/5e6eb3db-6731-467e-89d0-63411f226eb8)

**Comment by drperstry** [comment]
also I had to reposition the tsd folder to the scripts folder, in order to fix another issue.

![image](https://github.com/rajyraman/Levelup-for-Dynamics-CRM/assets/71937375/8454a723-311d-4daf-9edf-80269a7eb0c2)

**Comment by drperstry** [comment]
I removed gulp and used webpack only and did all configuration as gulp.

now it is built with same behavior and optimized, closing.

**Comment by impr3ssi0n** [comment]
@drperstry , Сould you post the actual change so I can build the project?

**Comment by rajyraman** [comment]
@impr3ssi0n - Since the versions or not upto date, try building in Dev Container with the config files on the repo.
