### ISSUE TITLE
Feature request - Open entity customization from entity record

### ISSUE THREAD

**Issue by altmank** [rajyraman/Levelup-for-Dynamics-CRM#31]
Hello,

I am not sure if this one is possible as I don't know if the specific form is URL addressable but I figured I'd ask in case you knew how to get to it. In CRM 2011, you used to be able to from an entity form, using the ribbon, open the entity customization screen. It seems likely that the ability to navigate to a URL to get to that entity customization screen may still exist in the newest versions. 

Essentially I would want that ability back in the form of a quick navigation link from the Level Up extension, it would call the Xrm.Page.data.entity.getEntityName() to determine what entity type you were on (if on a record instance page, it would not be available elsewhere) and then open up the generic customization page to that entity.

**Comment by rajyraman** [comment]
I thought about this initially. But there is one issue with this. When you do this it opens the default solution with the default publisher. Most people would not have changed the default publisher prefix which is "new". That will be a problem if people have been creating fields with a different publisher prefix.

**Comment by altmank** [comment]
I agree entirely if your goal is to create new customization, I would not want to do it under the default solution in most cases. However for me personally, my main use case is to just jump into customization to review them as a reference. I'll often want to glance quickly at the field list, get the options in an optionset, read a description, or go to the views and lookup filter criteria.

**Comment by rajyraman** [comment]
I can do it, but I have to add some notes about the new field publisher prefix issue or provide a way to choose a specific solution.
