### ISSUE TITLE
[BUG]: No functionality working in work environment

### ISSUE THREAD

**Issue by ElliotFraser-Kaplan** [rajyraman/Levelup-for-Dynamics-CRM#331]
**Describe the bug**

When I try to use Level Up in my work environment it does not seem to work at all. None of the buttons seem to work. However, in my personal tenant it all works fine. Both are using the same machine and browser (edge). 

**Desktop (please complete the following information):**
 - Browser - Edge
 - Dynamics 365/Power Apps Version - Latest
 - Admin
 - Online
 - Unified Interface
 - Model Driven App
 - Entity name, if it is an out-of-the-box entity - All effected, custom and ootb

**To Reproduce**

Downloaded Level Up
Clicked buttons ie Logical Names or God Mode
Nothing happens

**Expected behavior**

Normal functionality

**Screenshots**

n/a

**Videos**
If possible, attach a screen recording with sensitive and PII information blurred out.

n/a

**Additional context**
Add any other context about the problem here. e.g. browser Dev  Tools output

Let me know if I can provide anything else. Thanks for the awesome tool!

**Comment by rajyraman** [comment]
@ElliotFraser-Kaplan - Did you refresh the model driven app tab after installing the extension?

**Comment by ElliotFraser-Kaplan** [comment]
Wow I really should have thought of that before posting haha! Thanks that's resolved the issue
