### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by altmank** [rajyraman/Levelup-for-Dynamics-CRM#35]
I despise the behavior of links in the latest version of CRM, the fact that we can't actually use the browser context menus on them to open in new windows. Have you investigated this at all? What level of effort do you think it would be to start replacing lookups and other links with actual links directly to record pages in the DOM?

**Comment by altmank** [comment]
Another approach might be to add context events to all the links that show an open in new window menu.

**Comment by rajyraman** [comment]
This looks like lot of effort + the purpose of this extension is not to change the core behaviour of CRM. A greasemonkey script might be a better fit for this functionality.
