### ISSUE TITLE
God Mode - Contract Activated

### ISSUE THREAD

**Issue by rbento149** [rajyraman/Levelup-for-Dynamics-CRM#36]
Hi,

I am wondering is it possible to edit fields on an activated contract in God Mode as when I try I receive the following error "The status of the contract does not allow this action. If you contact support, please provide the technical details."

**Comment by rajyraman** [comment]
Don't think this is possible as the contract is not in an editable state when it is activated. There might be some platform level checks to prevent this from happening.
