### ISSUE TITLE
Using "Minimum Values" replaces values of text attribues with "string" 

### ISSUE THREAD

**Issue by thuld** [rajyraman/Levelup-for-Dynamics-CRM#4]
For instance the value for attribute "Topic" at opportunity level is replaced with "string". The error message "Value is not an array" is displayed.

**Comment by rajyraman** [comment]
The source of the script is https://community.dynamics.com/crm/b/magnetismsolutionscrmblog/archive/2014/12/08/microsoft-dynamics-crm-2013-populating-required-fields-with-bookmarklets.

Tried this on a new opportunity form in CRMOnline and I get the error in the currency field. I will look into this today.

**Comment by rajyraman** [comment]
"string" is the default value for the text field. The array error is no longer happening.
