### ISSUE TITLE
Level up not supported in latest build Version 1612 (8.2.1.176)?

### ISSUE THREAD

**Issue by Daniel-at-VNS** [rajyraman/Levelup-for-Dynamics-CRM#40]
noticed after updating to u2 that Level Up, clone at least, no longer works.  Is this a known issue?

**Comment by rajyraman** [comment]
The logic to enable disable the extension seems to be broken with 8.2 as the script I check is no longer there. I have changed this now and should work with 2.4. Is the extension enabled or is it just the cloning that no longer works? I am wondering whether this is related to #39 ?

**Comment by Daniel-at-VNS** [comment]
Correct - 39 and I are on the same team.  You said it should work with 2.4 but we're running 2.5.2 and it still does not work.  Stopped working right after we moved to 8.2.1.176.  Nobody else has reported this?

**Comment by rajyraman** [comment]
I am on vacation this week. I will look into this next week. If you keep devtools open, you might get some additional info on the error.

**Comment by rajyraman** [comment]
I tried this today in Dynamics 365 v9 + Chrome 62 + Level up v 2.5.2 and it worked without any issue for contact and client. What are your environment details and did you check the console for any errors?

**Comment by Daniel-at-VNS** [comment]
Deepthi please handle this.

Thank you.

Daniel Duffy – CEO / CIO
MCSE, Citrix CCA, HP ASE/ASP/ASC, Cisco CSE, Nimble NSP, STS/SSE+, Altiris ACE
Email: daniel.duffy@vns.net • URL: www.vns.net<http://www.vns.net>
Voice: (559) 650-2600, Ext. 300 • Fax: (559) 650-2601
364 West Fallbrook Avenue, #101 • Fresno, California  93711-5858

Valley Network Solutions - Providing Excellence in Technology™
Managed/Cloud Services • Network Design, Sales and Support • Structured Voice/Data Cabling & Fiber
Check us out on: Facebook<http://www.facebook.com/pages/Valley-Network-Solutions/109739029056936>  |  Twitter<https://twitter.com/#!/VNSnet>  |  LinkedIn<http://www.linkedin.com/company/valley-network-solutions>  |  Google<http://maps.google.com/maps/place?cid=2569974332848208054>

**Comment by Daniel-at-VNS** [comment]
Hi Natraj,

On Behalf of Daniel, I’m sending in details of error for clone record & logical names @ console

Console error on clone record with script – length undefined

[cid:image001.png@01D3621E.618A7080]
Level up extension js error

[cid:image002.png@01D3621E.618A7080]

On VM 1288
[cid:image003.png@01D3621E.618A7080]

Started showing problem on logical names feature also.

Environmental Details

Dynamics 365
[cid:image004.png@01D3621E.A5FF28A0]

Chrome 62 +

Level up v 2.5.2

Deepthi Thotakura – Developer

Email: deepthi.thotakura@vns.net • URL: www.vns.net<http://www.vns.net>
Voice: (559) 650-2600, Ext. 329 • Fax: (559) 650-2601
364 West Fallbrook Avenue, #101 • Fresno, California  93711-5858

Valley Network Solutions - Providing Excellence in Technology™
Managed/Cloud Services • Network Design, Sales and Support • Structured Voice/Data Cabling & Fiber
Check us out on: Facebook<http://www.facebook.com/pages/Valley-Network-Solutions/109739029056936>  |  Twitter<https://twitter.com/#!/VNSnet>  |  LinkedIn<http://www.linkedin.com/company/valley-network-solutions>  |  Google<http://maps.google.com/maps/place?cid=2569974332848208054>

From: Daniel F. Duffy
Sent: Sunday, November 19, 2017 7:29 PM
To: Deepthi X. Thotakura <Deepthi.Thotakura@vns.net>
Cc: Author <author@noreply.github.com>; rajyraman/Levelup-for-Dynamics-CRM <reply@reply.github.com>; rajyraman/Levelup-for-Dynamics-CRM <Levelup-for-Dynamics-CRM@noreply.github.com>
Subject: RE: [rajyraman/Levelup-for-Dynamics-CRM] Level up not supported in latest build Version 1612 (8.2.1.176)? (#40)

Deepthi please handle this.

Thank you.

Daniel Duffy – CEO / CIO
MCSE, Citrix CCA, HP ASE/ASP/ASC, Cisco CSE, Nimble NSP, STS/SSE+, Altiris ACE
Email: daniel.duffy@vns.net<mailto:daniel.duffy@vns.net> • URL: www.vns.net<http://www.vns.net>
Voice: (559) 650-2600, Ext. 300 • Fax: (559) 650-2601
364 West Fallbrook Avenue, #101 • Fresno, California  93711-5858

Valley Network Solutions - Providing Excellence in Technology™
Managed/Cloud Services • Network Design, Sales and Support • Structured Voice/Data Cabling & Fiber
Check us out on: Facebook<http://www.facebook.com/pages/Valley-Network-Solutions/109739029056936>  |  Twitter<https://twitter.com/#!/VNSnet>  |  LinkedIn<http://www.linkedin.com/company/valley-network-solutions>  |  Google<http://maps.google.com/maps/place?cid=2569974332848208054>

**Comment by rajyraman** [comment]
Cannot see the screenshots. Can you please upload them from GitHub?
