### ISSUE TITLE
Injecting Sdk.Soap.min.js breaks CRM REST Builder

### ISSUE THREAD

**Issue by jlattimer** [rajyraman/Levelup-for-Dynamics-CRM#42]
Hello - this is Jason, I make [CRM REST Builder](https://github.com/jlattimer/CRMRESTBuilder). I noticed with this most recent update you changed something with how your scripts get loaded, as it turns out we're both using Sdk.Soap.min.js. The issue is mine is a slightly older version (and maybe had a tweak or two besides, I can't remember now) but now that your version appears to be loading last my code is then hitting your copy and causing an error. 

Was wondering if maybe we can't put our heads together and figure out a way around this?

Is it conceivable to maybe change the Sdk namespace name in your implementation to something else? I'm hoping that wouldn't be too much effort and then we'd avoid collisions. 

Thoughts?

**Comment by rajyraman** [comment]
I am using Sdk.Soap for the user/roles page. I will change my name as that will be easiest.

**Comment by rajyraman** [comment]
Fixed with v2.5.1
