### ISSUE TITLE
Port extension to Edge?

### ISSUE THREAD

**Issue by seanmcne** [rajyraman/Levelup-for-Dynamics-CRM#43]
Hi, have you looked at testing the extension for Edge and listing it in the windows store?

**Comment by rajyraman** [comment]
I already have a repo [Levelup for Edge](https://github.com/rajyraman/Level-up-for-Dynamics-CRM-365-Edge-Browser) that I ported using [Edge Extension Toolkit](https://www.microsoft.com/en-AU/store/p/microsoft-edge-extension-toolkit/9nblggh4txvb).

I don't think it is up to date though. I am currently rewriting the whole extension using TypeScript. I will publish this to the store once I complete this.

**Comment by rajyraman** [comment]
"npm run edge" should now build the edge extension. I will look into how to publish this to the windows store.

**Comment by seanmcne** [comment]
Wow, great!  I'll look into this when I get some free cycles. Thanks!
