### ISSUE TITLE
Add Create Field Button

### ISSUE THREAD

**Issue by tpmeredith** [rajyraman/Levelup-for-Dynamics-CRM#48]
Would it be possible to add a "Create Field" button for whatever entity you have currently open? For example, if you have a contact currently open and you click "Create Field" it opens a new field window for that entity. So you dont have to go all the way to customize or open a form and click new field. Not that its a whole lot of extra clicks just saves ~5-10 seconds of loading pages.

**Comment by rajyraman** [comment]
The problem that would be it would use the publisher prefix of the default solution publisher, which is "new".
