### ISSUE TITLE
Forms section is suddenly missing

### ISSUE THREAD

**Issue by rbrady2017** [rajyraman/Levelup-for-Dynamics-CRM#49]
I can still see Navigation, Grid and Service Calls, but the entire Forms section (including my most-used God Mode) is gone. I tried deleting and reinstalling the extension, but had the same result. Thanks for your help.

![image](https://user-images.githubusercontent.com/32184266/30726533-064f1cea-9f11-11e7-8715-f2ff1b322bd1.png)

**Comment by rbrady2017** [comment]
Should have said -- Chrome Version 61.0.3163.91, and both CRM 2015 and Dynamics 365 on-prem.

**Comment by rajyraman** [comment]
Is this a legacy form with ribbon instead of command bar?
