### ISSUE TITLE
Logical names broken in v9

### ISSUE THREAD

**Issue by rajyraman** [rajyraman/Levelup-for-Dynamics-CRM#55]
If I click show logical names it only shows the tab and grid names but not the logical names of the different fields on the form with Dynamics 365 v9.0

-Reported from Chrome extension support page

**Comment by Mutnat** [comment]
@rajyraman yeah I've noticed this as well.  Would love to see this resolved soon, I've got a couple of different client projects going on right now in v9, and in the past I have used this feature of Level Up pretty extensively.  Pretty please?  :)
