### ISSUE TITLE
UI for version 2.6.2 does not match documentation

### ISSUE THREAD

**Issue by scottgolightly** [rajyraman/Levelup-for-Dynamics-CRM#56]
I installed the extension from the Chrome store today and the UI does not look like the documentation on this site. The labels on the buttons are different and as far as I can tell clicking on the buttons doesn't do anything.
![image](https://user-images.githubusercontent.com/4343718/35418146-e7519daa-01ed-11e8-8e1d-c6fd2d41ace0.png)

**Comment by scottgolightly** [comment]
After creating this issue I noticed some other functionality that wasn't working. I turned off the uBlock Origin extension and refreshed the page. All of the missing functionality was restored. I tried turning on uBlock Origin again so I could report what exactly was being blocked but now the UI looks as I would expect and the buttons work. Instead of 9 items blocked I only see a single block of a call to bing.com. I should have looked at the logs before turning off the extension.

**Comment by rajyraman** [comment]
When I updated the readme, I did not update the screenshot. I will do that soon. Since the extension script is injected into the page, the page needs to be refreshed manually after the extension is installed/updated on all the open tabs/windows.
