### ISSUE TITLE
Missing Sections

### ISSUE THREAD

**Issue by MichaelSnow504** [rajyraman/Levelup-for-Dynamics-CRM#57]
The only sections I have available are navigation and Misc. The Forms and Settings sections are not available.

**Comment by MichaelSnow504** [comment]
![image](https://user-images.githubusercontent.com/36487547/36223858-b66a1ad6-1193-11e8-9d2b-1df39a83c728.png)

**Comment by rajyraman** [comment]
Did you install or update the extension recently? If so, try refreshing the page.

**Comment by MichaelSnow504** [comment]
Yes.  Thank you that worked!


"We help you help people"

Michael Snow
Software Support Specialist
All Medical Personnel
Direct: 972-427-1140
Main: 800-706-2378
Michael.Snow@allmedical.com<mailto:Michael.Snow@allmedical.com>

[AMP Logo]<http://www.allmedical.com>
