### ISSUE TITLE
Limiting security permissions?

### ISSUE THREAD

**Issue by amervitz** [rajyraman/Levelup-for-Dynamics-CRM#59]
I do not have any experience with Chrome extension development, please bear with me if this is a silly question.

Have any attempts been made at only using the [activeTab](https://developer.chrome.com/extensions/permission_warnings#activeTab_permission) permission? Presently the permissions required are more than I'm comfortable with granting.

https://github.com/rajyraman/Levelup-for-Dynamics-CRM/blob/efb6b937d32998c6c1ec2fc3669d8c769c840475/app/manifest.json#L26-L31

This presently causes this warning during installation, which raises my alarm bells:
![image](https://user-images.githubusercontent.com/10599498/41442960-44d4c016-6ff7-11e8-9051-0a3f7cb6f85c.png)

Chrome documentation [says](https://developer.chrome.com/extensions/permission_warnings#permissions_with_warnings):

> It may be possible to avoid declaring any host permissions by using the activeTab permission

Based on documentation it sounds like the `activeTab` permission would still allow for the permissions required, but only obtain them for the specific tab the extension is used on when it is interacted with, which is a lot safer than the current wildcard permissions.

**Comment by rajyraman** [comment]
As soon as you put anything in content_scripts om the manifest, it displays "Read and change all your data on the websites that you visit", with nothing in the permission at all. But app.js needs to be injected into the dynamics page for this extension to work.
