### ISSUE TITLE
Impossible to cancel `Open record by id` action

### ISSUE THREAD

**Issue by shytikov** [rajyraman/Levelup-for-Dynamics-CRM#6]
When you start `Open record by id` action and press `Cancel` on first prompt, extension disregards this command, shows second prompt, and then opens new tab with error (what is expected in this case, since no entity name or entityid was given).
<br />
<br />Desired behavior: obey `Cancel` command and stop execution of the action.

**Comment by rajyraman** [comment]
Fixed in v1.3
