### ISSUE TITLE
LevelUp in Unified Interface

### ISSUE THREAD

**Issue by pmalecka** [rajyraman/Levelup-for-Dynamics-CRM#60]
Hi rajyraman,

first of all, thanks for creating this wonderful tool.

I am trying to use it in the new Unified Interface in v9, the Levelup Extension seems inactive.

The most wanted feature for v9 is the god mode.

Thanks!
Peter

**Comment by rajyraman** [comment]
I have get this working soon, as well as I have started to work more on more on UCI as well. I haven't really sat down and worked on the extension for a few months now, due to project work. I will look into get this working soon.
