### ISSUE TITLE
Field logical name is not correct when field is added multiple times on form

### ISSUE THREAD

**Issue by wauters** [rajyraman/Levelup-for-Dynamics-CRM#61]
![image](https://user-images.githubusercontent.com/21986100/42044944-990835c4-7afa-11e8-85e2-ae63e2c6f7f6.png)

It seems to append "1" to it. 

The original bookmark JS does not have this issue (https://us.hitachi-solutions.com/blog/showing-entity-logical-names-on-form/).

**Comment by rajyraman** [comment]
Was able to reproduce. It is due to the fact in most scenarios, control name and attribute name are same, but when you have the same control multiple times, they will be different i.e. control name will have the 1 in the end. Fixed. Will release a version soon.
