### ISSUE TITLE
Stopped Working

### ISSUE THREAD

**Issue by FrankFenneran** [rajyraman/Levelup-for-Dynamics-CRM#63]
We're on Dynamics 365 version 8.2.2.2114 and everything stopped working this morning.  Buttons come up, but nothing happens when you click

**Comment by Ynoaparast** [comment]
The issue before this adresses this problem: https://github.com/rajyraman/Levelup-for-Dynamics-CRM/issues/62

He just uploaded a new version (2.9.0) of the extension. Get it from the Chrome Webshop and it should fix it.

**Comment by FrankFenneran** [comment]
Thanks.  That did the trick.
