### ISSUE TITLE
Object Type Codes

### ISSUE THREAD

**Issue by buus1** [rajyraman/Levelup-for-Dynamics-CRM#64]
It would be nice to have a shortcut to the list of object type codes, as they are often needed when debugging permission issues. Also the ability to enter the object type code an get the entity name in return would be nice.

Here's a link that describes the WebAPI Url that I use for debugging today:
https://community.dynamics.com/crm/b/bringyourcode2life/archive/2017/11/22/retrieve-object-type-codes-via-webapi-url

**Comment by MaherSaleem** [comment]
I've supported that in the following PR
https://github.com/rajyraman/Levelup-for-Dynamics-CRM/pull/127
