### ISSUE TITLE
Form section is missing

### ISSUE THREAD

**Issue by Marty84** [rajyraman/Levelup-for-Dynamics-CRM#71]
Hi,
I used Level Up for Dynamics 365 until yesterday without problem but tomorrow I missed "Forms Area" with god mode inside; I've only Navigations and Miscellaneous.
I've removed and installed again this app (now is Version 3.3.0), I've unistalled and installed again chrome Browser but I didn't fix the problem. Could you help me?
Thanks

**Comment by rajyraman** [comment]
Did you reload the CRM page after installing or updating the extension?

**Comment by Marty84** [comment]
Absolutely yes. I also restarted my PC, I haven't any idea why or what I can do to fix it.

**Comment by rajyraman** [comment]
Cannot repro. I can see the forms are both in classic and Unified Interface.
![image](https://user-images.githubusercontent.com/5035266/49215372-bf448300-f41c-11e8-9cc3-40145e184028.png)
![image](https://user-images.githubusercontent.com/5035266/49215407-d4b9ad00-f41c-11e8-97b5-e0da88409f22.png)

**Comment by rajyraman** [comment]
I am using Dynamics 365 online on v9.1. Are you using onprem?

**Comment by Marty84** [comment]
Yes, I'm using Dynamics onprem. 
I downloaded Power Pane and I find another way for my work.
