### ISSUE TITLE
Missing options firm section missing

### ISSUE THREAD

**Issue by thenerdynerd** [rajyraman/Levelup-for-Dynamics-CRM#75]
Hi there form section is missing for me.

Uninstalled and reinstalled refreshed page and cleared cache. Am on version 3.3.2. Any ideas?

![4C2B8ADB-BA97-47C6-BFAF-3CC21816664F](https://user-images.githubusercontent.com/17202561/60945594-e8e35800-a2e3-11e9-8f44-67093e678a8c.jpeg)

**Comment by rajyraman** [comment]
What version of Dynamics is this? I am able to see the form section in Dynamics 365 online.

**Comment by thenerdynerd** [comment]
It is 365 online. Cleared cache, tried different machines but appears to be the same. Is there a security setting or change needed to be made.

**Comment by rajyraman** [comment]
This is the specific line that checks if the current page is a form -> https://github.com/rajyraman/Levelup-for-Dynamics-CRM/blob/3c1e2526496bb5995a67f0adb83d5df656816dcc/app/scripts/app/app.ts#L43

Are none of these selectors non-existent: #crmFormHeaderTop, div[data-id="editFormRoot"], #editFormRoot?

**Comment by rajyraman** [comment]
I tried again today, just to check if it is just user record. It works for me fine.

![image](https://user-images.githubusercontent.com/5035266/61499591-2b571400-aa0b-11e9-874d-5f3d2a2c4b0e.png)

This is my version
![image](https://user-images.githubusercontent.com/5035266/61499646-56d9fe80-aa0b-11e9-9b25-dc94c50e4ecb.png)

**Comment by rajyraman** [comment]
I have supported the extension few minute ago. Can you please update the extension to v3.3.3, refresh the page and try again?
