### ISSUE TITLE
Customize button not working in UCI

### ISSUE THREAD

**Issue by ajitthescorpion** [rajyraman/Levelup-for-Dynamics-CRM#76]
When using UCI, customize button is not working on opened record. 

![Customize_Button_Not_Working](https://user-images.githubusercontent.com/54162135/63139383-429d1780-c032-11e9-9751-fd1a16f1316f.png)

**Comment by rajyraman** [comment]
Can repro. I should simply redirect to make.powerapps.com, if it is an UCI client.
