### ISSUE TITLE
Problems in using with New UCI and Wave2

### ISSUE THREAD

**Issue by Jobengaru** [rajyraman/Levelup-for-Dynamics-CRM#78]
Hi,

on the view "My Active Accounts"
![image](https://user-images.githubusercontent.com/50359989/64340155-c620a780-cfe5-11e9-97f1-9ba2b83e3b13.png)

I've tried tu use the feature "Quick Find fields"
![image](https://user-images.githubusercontent.com/50359989/64340047-8d80ce00-cfe5-11e9-8cb3-0ad10ae12f69.png)

The following Message ist shown to me:
![image](https://user-images.githubusercontent.com/50359989/64340199-e2244900-cfe5-11e9-9436-b822dbe8e690.png)

When will it be possible to use this fantastic tool on the new UCI (with Wave2)?

Kind Regards,

Jobengaru

**Comment by Jobengaru** [comment]
Hi again,
any idea, how i can go on?
Kind regards,
Jobengaru

**Comment by rajyraman** [comment]
Sorry I missed this due to work related stuff. I will look into this during the weekend. @Jobengaru

**Comment by Jobengaru** [comment]
Great! Thank you!
Regards,
Ferdinand (alias Jobengaru)

Am Mi., 25. Sept. 2019 um 01:55 Uhr schrieb Natraj Yegnaraman <
notifications@github.com>:

**Comment by Jobengaru** [comment]
Hi @rajyraman,
do you see a chance to go on with the UCI theme?
Best Reagrds
Ferdinand (alias Jobengaru)

**Comment by rajyraman** [comment]
Hi @Jobengaru - I tried this today, and haven't still figured out how to get the viewid from the DOM. The selector that used to work, does not work anymore.

**Comment by Jobengaru** [comment]
I find it incredibly unfortunate that this function, so highly valued by me, is no longer available.

**Comment by rajyraman** [comment]
Actually if you have anything > 3.4.3 it should be working.

**Comment by Jobengaru** [comment]
Sorry!!! You are great! It works well now - thx a lot!
