### ISSUE TITLE
Forms Missing

### ISSUE THREAD

**Issue by OpenWorks4742** [rajyraman/Levelup-for-Dynamics-CRM#79]
HI
I followed another thread stating their Forms was missing. I'm having the same issues. I've also tried all suggested actions in the thread as well.

**Comment by rajyraman** [comment]
Was this never working, or did this stop working only recently?

**Comment by OpenWorks4742** [comment]
It stopped in the last few weeks

Thank you,

Shauna Carlson
602.288.1120

**Comment by rajyraman** [comment]
It is a game of whack-a-mole. I use some marker scripts to identify whether the page is a form or not. MSFT might have changed something. I will look into it today. What is the region where you see this behaviour?

**Comment by OpenWorks4742** [comment]
I live in Phoenix, AZ

Thank you,

Shauna Carlson
602.288.1120

**Comment by rajyraman** [comment]
I cannot see this behaviour in Australia East yet. I will try this on a different GEO and see if I can repro this.

**Comment by OpenWorks4742** [comment]
It started working again…idk what happened

Thank you,

Shauna Carlson
602.288.1120
