### ISSUE TITLE
Extension should become disabled on sites which are not Dynamics CRM sites

### ISSUE THREAD

**Issue by shytikov** [rajyraman/Levelup-for-Dynamics-CRM#8]
It's a bit misleading that extension is enabled everywhere and does nothing on websites which are not Dynamics CRM.
<br />
<br />I believe it should be possible detect is current web-site is CRM or not. Either by analyzing headers (at least you can tell wherever this site ASP.NET or not), location (all CRM Online installations are easy detectable based on domain name), or by probing CRM endpoint locations, will you get `404` or not.

**Comment by rajyraman** [comment]
That is the problem I faced when I started building the extension. Ideally I want the script to be injected for specified sites from a config. The background script can then check the URL and inject the script to the page when a match is found. I will look into the approaches you have specified soon.

**Comment by rajyraman** [comment]
Fixed in v1.3
