### ISSUE TITLE
Publish in Firefox Addons

### ISSUE THREAD

**Issue by sirideain** [rajyraman/Levelup-for-Dynamics-CRM#81]
Please publish this extension in https://addons.mozilla.org/en-US/firefox/.

**Comment by chauhanprateek92** [comment]
Please do publish it

**Comment by rajyraman** [comment]
I did submit last time, but it was rejected.

**Comment by rajyraman** [comment]
Happy news 😁. You can now use my extension on Firefox as well. https://addons.mozilla.org/en-US/firefox/addon/level-up-for-d365-power-apps/
