### ISSUE TITLE
Color Options for new UI

### ISSUE THREAD

**Issue by NotEnoughCholula** [rajyraman/Levelup-for-Dynamics-CRM#83]
I can get used to the new UI. The "Tabs" (Forms, Navigation, Grid) mean less scrolling and the new features are nice.

But mother of god - MY EYES! The pink hurts, even during the daytime. And I miss the "Dynamics CRM Blue" that was previously there. Any chance you can add some color customization for both the top menu and the menu tiles? Just add an input for hex code or something. It would go a long way to reducing eye strain when in darkness.

**Comment by zaha** [comment]
Have to agree that the new UI is nice, but the colors are too bright. Please desaturate them to make them more easy for the eyes.

**Comment by rajyraman** [comment]
I changed the theme to Power Apps/Dynamics 365 colour scheme. Hopefully this is alright.
![image](https://user-images.githubusercontent.com/5035266/71965366-9fa0a080-3253-11ea-8a74-70a0c70c40f3.png)

**Comment by NotEnoughCholula** [comment]
Great! I love it! Thanks!!!

**Comment by altmank** [comment]
Thank you, I too found my eyes burning here.

**Comment by rajyraman** [comment]
The new version is live with colour changes.
