### ISSUE TITLE
Overlay display height is too small every other time

### ISSUE THREAD

**Issue by zaha** [rajyraman/Levelup-for-Dynamics-CRM#84]
Hi,

every other time (roughly every 4th or 5th) I open the new overlay looks like this:

![2020-01-07_chrome_9R2PeOXT4p](https://user-images.githubusercontent.com/1721211/71898181-f2e1f880-3158-11ea-91bf-d674d430aebc.png)

Closing and opening the overlay again a couple of times usually fixes the issue, but it's annyoing nevertheless.

**Comment by rajyraman** [comment]
I cannot see this behaviour. I am using the latest version or Chrome and Edge Chromium and see the popup normally. Are you on the latest version of Chrome?
![image](https://user-images.githubusercontent.com/5035266/71965273-7718a680-3253-11ea-80e5-513fd5370672.png)

**Comment by zaha** [comment]
I was actually on Chrome Version 79.0.3945.88

I updated to the latest version. The issue is still there for me, but happens a lot less. E.g. it happened only twice after clicking over a dozen times in quick succession (which is not how you would typically use it). Before it was happening on a regular basis during regular use.

**Comment by Roland80** [comment]
I get this only on Vivaldi browser (version 2.9.1705.41). Haven't yet seen this happen on Chrome.

**Comment by sylwestrzak** [comment]
I have the same issue with my chrome Version 77.0.3865.75. In my case I can't use it... but need it urgently. Any solution and idea?

**Comment by rajyraman** [comment]
@sylwestrzak - Can you install this in Edge Chromium or latest version of Chrome and and see if this issue happens? The problem is due to recent Chrome Store changes, I cannot update the extension straight away as approval process take 3-4 days. Since I don't have an old version of Chrome I am unable to repro this issue.

**Comment by NotEnoughCholula** [comment]
Version 79.0.3945.88 (Official Build) (64-bit) Chrome for me, I get it intermittently.  Can't reliably reproduce. I refresh the page and it solves the problem.

**Comment by rajyraman** [comment]
@sylwestrzak @NotEnoughCholula - I have set a min-height for the container in the latest commit. Hopefully that will fix this issue.

**Comment by rajyraman** [comment]
@sylwestrzak @NotEnoughCholula - The new version 3.4.4 has been published. I have set the min-height for the popup. Can you please check if this is still an issue?

**Comment by sylwestrzak** [comment]
@rajyraman thanks, it works again :)
