### ISSUE TITLE
Firewalled On-Premise Environment

### ISSUE THREAD

**Issue by BetimBeja** [rajyraman/Levelup-for-Dynamics-CRM#87]
Hello,
I am having a problem with the new UI in v3.4.1 using the extension in a Dynamics v8.2.3 On-Premise in a firewalled environment. I think the Icons are being loaded from external sources and the end result is:
![image](https://user-images.githubusercontent.com/11160171/72156354-a21b0b80-33b5-11ea-9a54-75885949d41b.png)

Best regards,
Betim.

**Comment by rajyraman** [comment]
Material icons are loaded externally from Google CDN. Is this blocked for you?

https://github.com/rajyraman/Levelup-for-Dynamics-CRM/blob/13a496a02f9f6190521396f47ab19f7f8968e1f0/app/pages/options.html#L416

**Comment by BetimBeja** [comment]
Yes, the environment is actually with no internet access for my user.
